/************************************************************************
	This is the table that is used by all the <ctype> macros.
	The first entry is used so that EOF (which this file and UNIX
	assumes is -1) can be used by all the <ctype> macros.
	You will notice from all the macros in ctype.h that they
	begin with (_uctype+1) instead of _uctype.
	The table needs to support indexing by EOF or unsigned char
	values... the smallest unsigned char will have 256 possible
	values.  The macros will be suppressed for larger char sizes.

	Copyright 1986 Software Development Systems, Inc.
************************************************************************/
#include "clib.h"
#include "ctype.h"

const char _uctype[257] =
{
    /*  -1  */   0,
    /* 0x00 */  _C,
    /* 0x01 */  _C,
    /* 0x02 */  _C,
    /* 0x03 */  _C,
    /* 0x04 */  _C,
    /* 0x05 */  _C,
    /* 0x06 */  _C,
    /* 0x07 */  _C,
    /* 0x08 */  _C,
    /* 0x09 */  _S | _C,
    /* 0x0a */  _S | _C,
    /* 0x0b */  _S | _C,
    /* 0x0c */  _S | _C,
    /* 0x0d */  _S | _C,
    /* 0x0e */  _C,
    /* 0x0f */  _C,
    /* 0x10 */  _C,
    /* 0x11 */  _C,
    /* 0x12 */  _C,
    /* 0x13 */  _C,
    /* 0x14 */  _C,
    /* 0x15 */  _C,
    /* 0x16 */  _C,
    /* 0x17 */  _C,
    /* 0x18 */  _C,
    /* 0x19 */  _C,
    /* 0x1a */  _C,
    /* 0x1b */  _C,
    /* 0x1c */  _C,
    /* 0x1d */  _C,
    /* 0x1e */  _C,
    /* 0x1f */  _C,
    /* ' '  */  _S | _B,
    /* '!'  */  _P,
    /* '"'  */	_P,
    /* '#'  */  _P,
    /* '$'  */  _P,
    /* '%'  */  _P,
    /* '&'  */  _P,
    /* '''  */  _P,
    /* '('  */  _P,
    /* ')'  */  _P,
    /* '*'  */  _P,
    /* '+'  */  _P,
    /* ','  */  _P,
    /* '-'  */  _P,
    /* '.'  */  _P,
    /* '/'  */  _P,
    /* '0'  */  _N | _X,
    /* '1'  */  _N | _X,
    /* '2'  */  _N | _X,
    /* '3'  */  _N | _X,
    /* '4'  */  _N | _X,
    /* '5'  */  _N | _X,
    /* '6'  */  _N | _X,
    /* '7'  */  _N | _X,
    /* '8'  */  _N | _X,
    /* '9'  */  _N | _X,
    /* ':'  */  _P,
    /* ';'  */  _P,
    /* '<'  */  _P,
    /* '='  */  _P,
    /* '>'  */  _P,
    /* '?'  */  _P,
    /* '@'  */  _P,
    /* 'A'  */  _U | _X,
    /* 'B'  */  _U | _X,
    /* 'C'  */  _U | _X,
    /* 'D'  */  _U | _X,
    /* 'E'  */  _U | _X,
    /* 'F'  */  _U | _X,
    /* 'G'  */  _U,
    /* 'H'  */  _U,
    /* 'I'  */  _U,
    /* 'J'  */  _U,
    /* 'K'  */  _U,
    /* 'L'  */  _U,
    /* 'M'  */  _U,
    /* 'N'  */  _U,
    /* 'O'  */  _U,
    /* 'P'  */  _U,
    /* 'Q'  */  _U,
    /* 'R'  */  _U,
    /* 'S'  */  _U,
    /* 'T'  */  _U,
    /* 'U'  */  _U,
    /* 'V'  */  _U,
    /* 'W'  */  _U,
    /* 'X'  */  _U,
    /* 'Y'  */  _U,
    /* 'Z'  */  _U,
    /* '['  */  _P,
    /* '\'  */  _P,
    /* ']'  */  _P,
    /* '^'  */  _P,
    /* '_'  */  _P,
    /* '`'  */  _P,
    /* 'a'  */  _L | _X,
    /* 'b'  */  _L | _X,
    /* 'c'  */  _L | _X,
    /* 'd'  */  _L | _X,
    /* 'e'  */  _L | _X,
    /* 'f'  */  _L | _X,
    /* 'g'  */  _L,
    /* 'h'  */  _L,
    /* 'i'  */  _L,
    /* 'j'  */  _L,
    /* 'k'  */  _L,
    /* 'l'  */  _L,
    /* 'm'  */  _L,
    /* 'n'  */  _L,
    /* 'o'  */  _L,
    /* 'p'  */  _L,
    /* 'q'  */  _L,
    /* 'r'  */  _L,
    /* 's'  */  _L,
    /* 't'  */  _L,
    /* 'u'  */  _L,
    /* 'v'  */  _L,
    /* 'w'  */  _L,
    /* 'x'  */  _L,
    /* 'y'  */  _L,
    /* 'z'  */  _L,
    /* '{'  */  _P,
    /* '|'  */  _P,
    /* '}'  */  _P,
    /* '~'  */  _P,
    /* 0x7f */  _C,
    0                   /* 0x80-0xFF are all zero */
};

#if VMS
_pullctyp() {}  /* needed when testing with some resident linkers */
#endif
