#ifndef MY_SSAPI_CODES_H__
#define MY_SSAPI_CODES_H__

//************************************************************************
//				SSAPI TYPE CODES
//************************************************************************

enum SSAPI_VALUESET_TYPES{
	SSAPI_TYPE_STRING		= 0,
	SSAPI_TYPE_INT 			= 1,
	SSAPI_TYPE_FLOAT 		= 2,
	SSAPI_TYPE_VECTOR 		= 3,
	SSAPI_TYPE_BOOLEAN		= 4,
	SSAPI_TYPE_GENERIC 		= 5,
	SSAPI_TYPE_INT_64 		= 6,
	SSAPI_TYPE_U8			= 7,
	SSAPI_TYPE_U16			= 8,
	SSAPI_TYPE_U64			= 9,
	SSAPI_TYPE_INT8			= 10,
	SSAPI_TYPE_INT16		= 11,
	SSAPI_TYPE_U32			= 12,
	SSAPI_TYPE_ROW_ID		= 13
};

//************************************************************************
//				TRANSPORT INTERNALS
//************************************************************************
#define SSAPI_TRANSPORT_SESSION_ID 0
#define SSAPI_INTERNAL_VALUE_HEADER_SIZE 5

//message priorities
#define SSAPI_PRIORITY_LOWEST 0
#define SSAPI_PRIORITY_FILE_UPLOAD 1

//************************************************************************
//				R C s	F O R	S S A P I	R E Q U E S T S
//************************************************************************
//globals

enum SSAPI_RC_SETS_AND_ELSE{
	SSAPI_RC_SUCCESS					=				0,
	SSAPI_RETURN_STATUS_SET				=				0,
	SSAPI_RETURN_STATUS					=				0,	// 1st value in the return set
	SSAPI_EXCEPTION_STRING_ID			=				1	// 2nd value in the return set (only for errors)
};

// EXCEPTIONS
#define SSAPI_EXCEPTION_INTERNAL							1
#define SSAPI_EXCEPTION_SECURITY							2
#define SSAPI_EXCEPTION_CAPABILITIES						3
#define SSAPI_EXCEPTION_INVALID_PARAMETER					4
#define SSAPI_EXCEPTION_SW_VERSION_MISMATCH					5
#define SSAPI_EXCEPTION_INVALID_CONFIG_ID					6
#define SSAPI_EXCEPTION_INVALID_STATE						7	


//************************************************************************
//
//
//				O B J E C T		M A N A G E R		I D s
//
//
//************************************************************************

#define	SSAPI_MANAGER_CLASS_TYPE_USER_MANAGER				1
#define SSAPI_MANAGER_CLASS_TYPE_PHS_DATA_MANAGER			2
#define SSAPI_MANAGER_CLASS_TYPE_DEVICE_MANAGER				3
#define SSAPI_MANAGER_CLASS_TYPE_ALARM_MANAGER				4
#define SSAPI_MANAGER_CLASS_TYPE_HOST_MANAGER				5
#define SSAPI_MANAGER_CLASS_TYPE_LOG_MANAGER				6
#define SSAPI_MANAGER_CLASS_TYPE_LUN_MANAGER				7
#define SSAPI_MANAGER_CLASS_TYPE_PROCESS_MANAGER			8
#define SSAPI_MANAGER_CLASS_TYPE_STORAGE_MANAGER			9
#define SSAPI_MANAGER_CLASS_TYPE_SOFTWARE_UPDATE_MANAGER	10
#define	SSAPI_MANAGER_CLASS_TYPE_CONFIG_ID_MANAGER			11
#define	SSAPI_MANAGER_TYPE_TABLE_MANAGER					12
#define	SSAPI_MANAGER_CLASS_TYPE_PROFILE_MANAGER			13
#define	SSAPI_MANAGER_CLASS_TYPE_CONNECTION_MANAGER			14


//************************************************************************
//	OBJECT MANAGER REQUEST CODES 
//************************************************************************

//ObjectManager::List()
#define	SSAPI_OBJECT_MANAGER_LIST							0	// <--
	#define SSAPI_OBJECT_MANAGER_LIST_FILTER_SET				0	// 1st in-parm
	#define SSAPI_OBJECT_MANAGER_LIST_OBJECT_VECTOR				1	// 2nd out-parm
//ObjectManaer::AddListener()
#define SSAPI_OBJECT_MANAGER_ADD_LISTENER					1	// <--
	#define SSAPI_OBJECT_MANAGER_ADD_LISTENER_LISTENER_TYPE		0	// 1st in-parm
	#define SSAPI_OBJECT_MANAGER_ADD_LISTENER_EVENT_OBJECT		1	// 2nd out-parm, added with every request after 1st one
//ObjectManager::DeleteListener()
#define	SSAPI_OBJECT_MANAGER_DELETE_LISTENER				2	// <--
	#define SSAPI_OBJECT_MANAGER_DELETE_LISTENER_LISTENER_TYPE	0	// 1st in-parm
#if 0
//ObjectManager::UpdateManagedObjectMember()
#define SSAPI_OBJECT_MANAGER_UPDATE_MANAGED_OBJECT_MEMBER	3
	#define SSAPI_OBJECT_MANAGER_UPDATE_MANAGED_OBJECT_MEMBER_VALUE 0
	#define SSAPI_OBJECT_MANAGER_UPDATE_MANAGED_OBJECT_MEMBER_OBJECT_CODE 1
	#define SSAPI_OBJECT_MANAGER_UPDATE_MANAGED_OBJECT_MEMBER_FIELD_ID 2
#endif
//ManagedObject::AddListener() - via ObjectManager
#define SSAPI_MANAGED_OBJECT_ADD_LISTENER					4	// <--
	#define	SSAPI_MANAGED_OBJECT_ADD_LISTENER_OWNER_ID			0	// in
	#define SSAPI_MANAGED_OBJECT_ADD_LISTENER_LISTENER_TYPE		1	// in
	#define SSAPI_MANAGED_OBJECT_ADD_LISTENER_OBJECT_ID			2	// in
	#define SSAPI_MANAGED_OBJECT_ADD_LISTENER_EVENT_OBJECT		1	// 2nd out-parm, done starting from 2nd reply
//ManagedObject::DeleteListener() - via ObjectManager
#define	SSAPI_MANAGED_OBJECT_DELETE_LISTENER				5	// <--
	#define	SSAPI_MANAGED_OBJECT_DELETE_LISTENER_OWNER_ID		0	// in
	#define SSAPI_MANAGED_OBJECT_DELETE_LISTENER_LISTENER_TYPE	1	// in
	#define SSAPI_MANAGED_OBJECT_DELETE_LISTENER_OBJECT_ID		2	// in
//ObjectManager::PagedList()
#define SSAPI_OBJECT_MANAGER_PAGED_LIST						6
	#define	SSAPI_OBJECT_MANAGER_PAGED_LIST_FILTER_SET			0	// in
	#define SSAPI_OBJECT_MANAGER_PAGED_LIST_FIELD_ID			1	// in
	#define SSAPI_OBJECT_MANAGER_PAGED_LIST_START_VALUE			2	// in
	#define SSAPI_OBJECT_MANAGER_PAGED_LIST_DIRECTION			3	// in
	#define SSAPI_OBJECT_MANAGER_PAGED_LIST_PAGE_SIZE			4	// in
	#define SSAPI_OBJECT_MANAGER_PAGED_LIST_OBJECT_VECTOR		1	// 2nd out-parm
//ObjectManager::AddObject()
#define SSAPI_OBJECT_MANAGER_ADD_OBJECT						7
	#define SSAPI_OBJECT_MANAGER_ADD_OBJECT_OBJECT				0	// in
//ObjectManager::ModifyObject()
#define SSAPI_OBJECT_MANAGER_MODIFY_OBJECT					8
	#define SSAPI_OBJECT_MANAGER_MODIFY_OBJECT_OBJECT			0	// in
//ObjectManager::DeleteObject()
#define SSAPI_OBJECT_MANAGER_DELETE_OBJECT					9
	#define SSAPI_OBJECT_MANAGER_DELETE_OBJECT_OBJECT			0	// in


#define SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST			10		// <-- the last!


//************************************************************************
//
//			U S E R		M A N A G E R	R E Q U E S T S
//
//************************************************************************
//UserManager::Login()
#define SSAPI_USER_MANAGER_LOGIN						(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 1)
	#define SSAPI_USER_MANAGER_LOGIN_OBJECT					0	// in
	#define SSAPI_USER_MANAGER_LOGIN_USER_OBJECT			1	// in
//UserManager::Logout()
#define SSAPI_USER_MANAGER_LOGOUT						(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 2)
	#define SSAPI_USER_MANAGER_LOGOUT_OBJECT				0	// in
//UserManager::ChangePassword()
#define SSAPI_USER_MANAGER_CHANGE_PASSWORD				(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 3)
	#define SSAPI_USER_MANAGER_CHANGE_PASSWORD_OBJECT_ID	0  // in
	#define SSAPI_USER_MANAGER_CHANGE_PASSWORD_OLD_PASSWORD 1  // in
	#define SSAPI_USER_MANAGER_CHANGE_PASSWORD_NEW_PASSWORD 2  // in

#define SSAPI_USER_MANAGER_LAST_REQUEST_ID				SSAPI_USER_MANAGER_CHANGE_PASSWORD


//************************************************************************
//
//			S T O R A G E		M A N A G E R	R E Q U E S T S
//
//************************************************************************

// StorageManager::AddArray( ValueSet array, ValueSet memberIds, ValueSet spareIds );
#define SSAPI_STORAGE_MANAGER_ADD_ARRAY					(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 1)
	#define SSAPI_STORAGE_MANAGER_ADD_ARRAY_CONFIG_ID_OBJECT	0	// in
	#define SSAPI_STORAGE_MANAGER_ADD_ARRAY_ARRAY_OBJECT		1	// in
	#define SSAPI_STORAGE_MANAGER_ADD_ARRAY_MEMBER_ID_VECTOR	2	// in
	#define SSAPI_STORAGE_MANAGER_ADD_ARRAY_SPARE_ID_VECTOR		3	// in

// StorageManager::AddDedicatedSpare( DesignatorId arrayId, DesignatorId newSpareId );
#define SSAPI_STORAGE_MANAGER_ADD_DEDICATED_SPARE		(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 2)
	#define SSAPI_STORAGE_MANAGER_ADD_DEDICATED_SPARE_CONFIG_ID_OBJECT	0	// in
	#define SSAPI_STORAGE_MANAGER_ADD_DEDICATED_SPARE_ARRAY_ID			1	// in
	#define SSAPI_STORAGE_MANAGER_ADD_DEDICATED_SPARE_NEW_SPARE_ID		2	// in

// StorageManager::AddPoolSpare( DesignatorId arrayId, DesignatorId newSpareId );
#define SSAPI_STORAGE_MANAGER_ADD_POOL_SPARE			(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 3)
	#define SSAPI_STORAGE_MANAGER_ADD_POOL_SPARE_CONFIG_ID_OBJECT	0	// in
	#define SSAPI_STORAGE_MANAGER_ADD_POOL_SPARE_POOL_ID			1	// in
	#define SSAPI_STORAGE_MANAGER_ADD_POOL_SPARE_NEW_SPARE_ID		2	// in

// StorageManager::DeleteDedicatedSpare( DesignatorId arrayId, DesignatorId spareId );
#define SSAPI_STORAGE_MANAGER_DELETE_DEDICATED_SPARE		(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 4)
	#define SSAPI_STORAGE_MANAGER_DELETE_DEDICATED_SPARE_CONFIG_ID_OBJECT	0	// in
	#define SSAPI_STORAGE_MANAGER_DELETE_DEDICATED_SPARE_ARRAY_ID			1	// in
	#define SSAPI_STORAGE_MANAGER_DELETE_DEDICATED_SPARE_SPARE_ID			2	// in

// StorageManager::DeletePoolSpare( DesignatorId arrayId, DesignatorId spareId );
#define SSAPI_STORAGE_MANAGER_DELETE_POOL_SPARE			(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 5)
	#define SSAPI_STORAGE_MANAGER_DELETE_POOL_SPARE_CONFIG_ID_OBJECT	0	// in
	#define SSAPI_STORAGE_MANAGER_DELETE_POOL_SPARE_POOL_ID				1	// in
	#define SSAPI_STORAGE_MANAGER_DELETE_POOL_SPARE_SPARE_ID			2	// in

// StorageManager::AddMemberToArray( DesignatorId arrayId, Designator Id newMemberId )
#define SSAPI_STORAGE_MANAGER_ADD_MEMBER				(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 6)
	#define SSAPI_STORAGE_MANAGER_ADD_MEMBER_CONFIG_ID_OBJECT			0	// in
	#define SSAPI_STORAGE_MANAGER_ADD_MEMBER_ARRAY_ID					1	// in
	#define SSAPI_STORAGE_MANAGER_ADD_MEMBER_NEW_MEMBER_ID				2	// in

// StorageManager::RemoveMemberFromArray( DesignatorId arrayId, Designator Id memberId )
#define SSAPI_STORAGE_MANAGER_REMOVE_MEMBER				(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 7)
	#define SSAPI_STORAGE_MANAGER_REMOVE_MEMBER_CONFIG_ID_OBJECT		0	// in
	#define SSAPI_STORAGE_MANAGER_REMOVE_MEMBER_ARRAY_ID				1	// in
	#define SSAPI_STORAGE_MANAGER_REMOVE_MEMBER_MEMBER_ID				2	// in

// StorageManager::DownArrayMember( DesignatorId arrayId, DesignatorId memberId )
#define	SSAPI_STORAGE_MANAGER_DOWN_MEMBER				(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 8)
	#define	SSAPI_STORAGE_MANAGER_DOWN_MEMBER_CONFIG_ID_OBJECT			0	// in
	#define	SSAPI_STORAGE_MANAGER_DOWN_MEMBER_ARRAY_ID					1	// in
	#define	SSAPI_STORAGE_MANAGER_DOWN_MEMBER_MEMBER_ID					2	// in

// StorageManager::SetPreferredReadMember( DesignatorId arrayId, DesignatorId memberId )
#define SSAPI_STORAGE_MANAGER_SET_PREF_MEMBER			(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 9)
	#define SSAPI_STORAGE_MANAGER_SET_PREF_MEMBER_CONFIG_ID_OBJECT		0	// in
	#define SSAPI_STORAGE_MANAGER_SET_PREF_MEMBER_ARRAY_ID				1	// in
	#define SSAPI_STORAGE_MANAGER_SET_PREF_MEMBER_MEMBER_ID				2	// in

// StorageManager::SetSourceMember( DesignatorId arrayId, DesignatorId memberId )
#define SSAPI_STORAGE_MANAGER_SET_SOURCE_MEMBER			(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 10)
	#define SSAPI_STORAGE_MANAGER_SET_SOURCE_MEMBER_CONFIG_ID_OBJECT	0	// in
	#define SSAPI_STORAGE_MANAGER_SET_SOURCE_MEMBER_ARRAY_ID			1	// in
	#define SSAPI_STORAGE_MANAGER_SET_SOURCE_MEMBER_MEMBER_ID			2	// in

// StorageManager::ChangeStorageElementName( DesignatorId elementId, UnicodeString newName );
#define	SSAPI_STORAGE_MANAGER_CHANGE_STORAGE_NAME		(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 11)
	#define	SSAPI_STORAGE_MANAGER_CHANGE_STORAGE_NAME_CONFIG_ID_OBJECT	0	// in 
	#define	SSAPI_STORAGE_MANAGER_CHANGE_STORAGE_NAME_ELEMENT_ID		1	// in
	#define	SSAPI_STORAGE_MANAGER_CHANGE_STORAGE_NAME_NEW_NAME			2	// in

// StorageManager::AddHotCopy( ValueSet array, ValueSet memberIds, RAID_UTIL_PRIORITY priority, DesignatorId memberToExportAtEnd = 0 );
#define SSAPI_STORAGE_MANAGER_ADD_HOT_COPY					(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 12)
	#define SSAPI_STORAGE_MANAGER_ADD_HOT_COPY_CONFIG_ID_OBJECT			0	// in
	#define SSAPI_STORAGE_MANAGER_ADD_HOT_COPY_ARRAY_OBJECT				1	// in
	#define SSAPI_STORAGE_MANAGER_ADD_HOT_COPY_MEMBER_ID_VECTOR			2	// in
	#define SSAPI_STORAGE_MANAGER_ADD_HOT_COPY_PRIORITY					3	// in
	#define SSAPI_STORAGE_MANAGER_ADD_HOT_COPY_EXPORT_MEMBER_ID			4	// in

// StorageManager::BreakHotCopy( DesignatorId arrayId, DesignatorId memberToExportId );
#define	SSAPI_STORAGE_MANAGER_BREAK_HOT_COPY				(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 14 ) // skip 13! :-)
	#define	SSAPI_STORAGE_MANAGER_BREAK_HOT_COPY_CONFIG_ID_OBJECT		0	// in	
	#define	SSAPI_STORAGE_MANAGER_BREAK_HOT_COPY_ARRAY_ID				1	// in
	#define	SSAPI_STORAGE_MANAGER_BREAK_HOT_COPY_EXPORT_MEMBER_ID		2	// in

// StorageManager::MergePartitions( ValueSet partitionIds );
#define	SSAPI_STORAGE_MANAGER_MERGE_PARTITIONS				(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 15 )
	#define	SSAPI_STORAGE_MANAGER_MERGE_PARTITIONS_CONFIG_ID_OBJECT		0	// in
	#define	SSAPI_STORAGE_MANAGER_MERGE_PARTITIONS_PARTITON_ID_VECTOR	1	// in

// StorageManager::CreatePartition( StorageElementPartition partition, UnicodeString remainderName )
#define	SSAPI_STORAGE_MANAGER_CREATE_PARTITION				(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 16 )
	#define	SSAPI_STORAGE_MANAGER_CREATE_PARTITION_CONFIG_ID_OBJECT		0	// in
	#define	SSAPI_STORAGE_MANAGER_CREATE_PARTITION_NEW_PARTITION_OBJECT	1	// in
	#define	SSAPI_STORAGE_MANAGER_CREATE_PARTITION_REMAINDER_NAME		2	// in

//************************************************************************
//
//			H O S T		M A N A G E R	R E Q U E S T S
//
//************************************************************************

// HostManager::SetConnectionIds( DesignatorId owner, ValueSet connectionIds )
#define	SSAPI_HM_SET_CONNECTION_IDS								(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 1)
	#define	SSAPI_HM_SET_CONNECTION_IDS_CONFIG_ID_OBJECT		0	// in
	#define	SSAPI_HM_SET_CONNECTION_IDS_OWNER_ID				1	// in			
	#define	SSAPI_HM_SET_CONNECTION_IDS_CONNECTION_ID_VECTOR	2	// in

//HostManager::AddConnection( DesignatorId owner, DesignatorId connId );
#define SSAPI_HM_ADD_CONNECTION_ID								(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 2)
	#define SSAPI_HM_ADD_CONNECTION_ID_CONFIG_ID_OBJECT			0	// in
	#define SSAPI_HM_ADD_CONNECTION_ID_OWNER_ID					1	// in
	#define SSAPI_HM_ADD_CONNECTION_ID_CONNECTION_ID			2	// in	
	#define SSAPI_HM_ADD_CONNECTION_ID_CONNECTION_FLAGS			3	// in, when applicable

//HostManager::RemoveConnection( DesignatorId owner, DesignatorId connId );
#define SSAPI_HM_REMOVE_CONNECTION_ID							(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 3)
	#define SSAPI_HM_REMOVE_CONNECTION_ID_CONFIG_ID_OBJECT		0	// in
	#define SSAPI_HM_REMOVE_CONNECTION_ID_OWNER_ID				1	// in
	#define SSAPI_HM_REMOVE_CONNECTION_ID_CONNECTION_ID			2	// in


//************************************************************************
//
//			C O N N E C T I O N		M A N A G E R	R E Q U E S T S
//
//************************************************************************


//DataPath::ModifyStrings
#define SSAPI_PATH_MODIFY_STRINGS								(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 1)
	#define SSAPI_PATH_MODIFY_STRINGS_CONFIG_ID_OBJECT			0	// in
	#define SSAPI_PATH_MODIFY_STRINGS_PATH_OBJECT				1	// in


//ConnectionManager::AddConnection( DesignatorId owner, DesignatorId connId );
#define SSAPI_CM_ADD_CONNECTION_ID								(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 2)
	#define SSAPI_CM_ADD_CONNECTION_ID_CONFIG_ID_OBJECT			0	// in
	#define SSAPI_CM_ADD_CONNECTION_ID_OWNER_ID					1	// in
	#define SSAPI_CM_ADD_CONNECTION_ID_CONNECTION_ID			2	// in	

//ConnectionManager::RemoveConnection( DesignatorId owner, DesignatorId connId );
#define SSAPI_CM_REMOVE_CONNECTION_ID							(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 3)
	#define SSAPI_CM_REMOVE_CONNECTION_ID_CONFIG_ID_OBJECT		0	// in
	#define SSAPI_CM_REMOVE_CONNECTION_ID_OWNER_ID				1	// in
	#define SSAPI_CM_REMOVE_CONNECTION_ID_CONNECTION_ID			2	// in

// ConnectionManager::SetConnectionIds( DesignatorId owner, ValueSet connectionIds )
#define	SSAPI_CM_SET_CONNECTION_IDS								(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 4)
	#define	SSAPI_CM_SET_CONNECTION_IDS_CONFIG_ID_OBJECT		0	// in
	#define	SSAPI_CM_SET_CONNECTION_IDS_OWNER_ID				1	// in			
	#define	SSAPI_CM_SET_CONNECTION_IDS_CONNECTION_ID_VECTOR	2	// in

//************************************************************************
//
//			D E V I C E		M A N A G E R	R E Q U E S T S
//
//************************************************************************

//DeviceManager::SetDeviceLocked( bool, DesignatorId )
#define SSAPI_DEVICE_MANAGER_SET_DEVICE_LOCKED						(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 1)
	#define SSAPI_DEVICE_MANAGER_SET_DEVICE_LOCKED_LOCKED			0	// in
	#define SSAPI_DEVICE_MANAGER_SET_DEVICE_LOCKED_OBJECT_ID		1	// in
//DeviceManager::SetDeviceInService( bool, DesignatorId )
#define SSAPI_DEVICE_MANAGER_SET_DEVICE_IN_SERVICE					(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 2)
	#define SSAPI_DEVICE_MANAGER_SET_DEVICE_IN_SERVICE_IN_SERVICE	0	// in
	#define SSAPI_DEVICE_MANAGER_SET_DEVICE_IN_SERVICE_OBJECT_ID	1	// in
//DeviceManager::SetDevicePowered( bool, DesignatorId )
#define SSAPI_DEVICE_MANAGER_SET_DEVICE_POWERED						(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 3)	
	#define SSAPI_DEVICE_MANAGER_SET_DEVICE_POWERED_POWERED			0	// in
	#define SSAPI_DEVICE_MANAGER_SET_DEVICE_POWERED_OBJECT_ID		1	// in


//************************************************************************
//
//			L U N	M A P	M A N A G E R	R E Q U E S T S
//
//************************************************************************

//LunManager::VerifyLun()
#define SSAPI_LUN_MANAGER_VERIFY_LUN					(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 1)
	#define SSAPI_LUN_MANAGER_VERIFY_LUN_CONFIG_ID_OBJECT			0	// in
	#define SSAPI_LUN_MANAGER_VERIFY_LUN_LUN_MAP_ENTRY_ID			1

//LunManager::Export()
#define SSAPI_LUN_MANAGER_EXPORT						(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 2)
	#define SSAPI_LUN_MANAGER_EXPORT_CONFIG_ID_OBJECT				0	// in
	#define SSAPI_LUN_MANAGER_EXPORT_LUN_MAP_ENTRY_ID				1	// in

//LunManager::Unexport()
#define SSAPI_LUN_MANAGER_UNEXPORT						(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 3)
	#define SSAPI_LUN_MANAGER_UNEXPORT_CONFIG_ID_OBJECT				0	// in
	#define SSAPI_LUN_MANAGER_UNEXPORT_LUN_MAP_ENTRY_ID				1	// in

//LunMapManager::ModifyStorageId( DesignatorId lunMap, StorageId storageId)
#define	SSAPI_LUN_MANAGER_MODIFY_STORAGE_ID				(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 4)
	#define	SSAPI_LUN_MANAGER_MODIFY_STORAGE_ID_LUN_MAP_ENTRY_ID	0	// in
	#define	SSAPI_LUN_MANAGER_MODIFY_STORAGE_ID_STORAGE_ID_OBJECT	1	// in


//************************************************************************
//
//			A L A R M	M A N A G E R	R E Q U E S T S
//
//************************************************************************

//AlarmManager::AcknowledgeAlarm()
#define SSAPI_ALARM_MANAGER_ACKNOWLEDGE_ALARM			(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 1)
	#define SSAPI_ALARM_MANAGER_ACKNOWLEDGE_ALARM_ALARM_ID		0	// in
	#define SSAPI_ALARM_MANAGER_ACKNOWLEDGE_ALARM_COMMENTS		1	// in

//AlarmManager::UnacknowledgeAlarm()
#define SSAPI_ALARM_MANAGER_UNACKNOWLEDGE_ALARM			(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 2)
	#define SSAPI_ALARM_MANAGER_UNACKNOWLEDGE_ALARM_ALARM_ID	0	// in 
	#define SSAPI_ALARM_MANAGER_UNACKNOWLEDGE_ALARM_COMMENTS	1	// in

//AlarmManager::ClearAlarm()
#define SSAPI_ALARM_MANAGER_CLEAR_ALARM					(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 3)
	#define SSAPI_ALARM_MANAGER_CLEAR_ALARM_ALARM_ID			0	// in
	#define SSAPI_ALARM_MANAGER_CLEAR_ALARM_COMMENTS			1	// in

// AlarmManager::AddNotes()
#define	SSAPI_ALARM_MANAGER_ADD_NOTES					(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 4)
	#define	SSAPI_ALARM_MANAGER_ADD_NOTES_ALARM_ID				0	// in
	#define	SSAPI_ALARM_MANAGER_ADD_NOTES_NOTES					1	// in



//************************************************************************
//
//			P R O C E S S	M A N A G E R	R E Q U E S T S
//
//************************************************************************

//ProcessManager::PauseProcess()
#define SSAPI_PROCESS_MANAGER_PAUSE_PROCESS				(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 1)
	#define SSAPI_PROCESS_MANAGER_PAUSE_PROCESS_PROCESS_ID		0	// in		
//ProcessManager::ResumeProcess()
#define SSAPI_PROCESS_MANAGER_RESUME_PROCESS			(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 2)
	#define SSAPI_PROCESS_MANAGER_RESUME_PROCESS_PROCESS_ID		0	// in


//************************************************************************
//
//			T A B L E	M A N A G E R	R E Q U E S T S
//
//************************************************************************

#define	SSAPI_TABLE_MANAGER_MODIFY_FIELD				(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 1)
	#define	SSAPI_TABLE_MANAGER_MODIFY_FIELD_ROW_ID				0	// in
	#define	SSAPI_TABLE_MANAGER_MODIFY_FIELD_FIELD_NAME			1	// in
	#define	SSAPI_TABLE_MANAGER_MODIFY_FIELD_NEW_VALUE			2	// in
	

//************************************************************************
//
//			S / W	U P D A T E		M A N A G E R	R E Q U E S T S
//
//************************************************************************

#define	SSAPI_SW_UPDATE_MANAGER_ADD_IMAGE				(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 1)
	#define	SSAPI_SW_UPDATE_MANAGER_ADD_IMAGE_BINARY_BLOB		0	// in
	#define	SSAPI_SW_UPDATE_MANAGER_ADD_IMAGE_BINARY_BLOB_SIZE	1	// in

#define	SSAPI_SW_UPDATE_MANAGER_SET_DEFAULT				(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 2)
	#define	SSAPI_SW_UPDATE_MANAGER_SET_DEFAULT_DESCRIPTOR_ID	0	// in

#define	SSAPI_SW_UPDATE_MANAGER_SET_PRIMARY				(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 3)
	#define	SSAPI_SW_UPDATE_MANAGER_SET_PRIMARY_IMAGE_ID		0	// in

#define	SSAPI_SW_UPDATE_MANAGER_ASSOCIATE_IMAGE			(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 4)
	#define	SSAPI_SW_UPDATE_MANAGER_ASSOCIATE_IMAGE_DESCRIPTOR_ID	0	// in
	#define	SSAPI_SW_UPDATE_MANAGER_ASSOCIATE_IMAGE_DEVICE_ID		1	// in

#define	SSAPI_SW_UPDATE_MANAGER_UNASSOCIATE_IMAGE		(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 5)
	#define SSAPI_SW_UPDATE_MANAGER_UNASSOCIATE_IMAGE_DESCRIPTOR_ID	0
	#define SSAPI_SW_UPDATE_MANAGER_UNASSOCIATE_IMAGE_DEVICE_ID		1

#define	SSAPI_SW_UPDATE_MANAGER_REMOVE_IMAGE			(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 6)
	#define	SSAPI_SW_UPDATE_MANAGER_REMOVE_IMAGE_IMAGE_DESCRIPTOR_ID	0	// in

#define	SSAPI_SW_UPDATE_MANAGER_BOOT_PRIMARY_IMAGE		(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 7)
	#define	SSAPI_SW_UPDATE_MANAGER_BOOT_PRIMARY_IMAGE_CONFIG_ID_	0	// in
	#define	SSAPI_SW_UPDATE_MANAGER_BOOT_PRIMARY_IMAGE_SLOT_NUMBER	1	// in

#define	SSAPI_SW_UPDATE_MANAGER_BOOT_PRIMARY_ALTERNATE_IMAGE (SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 8)
	#define	SSAPI_SW_UPDATE_MANAGER_BOOT_PRIMARY_ALTERNATE_IMAGE_CONFIG_ID		0	// in
	#define	SSAPI_SW_UPDATE_MANAGER_BOOT_PRIMARY_ALTERNATE_IMAGE_SLOT_NUMBER	1	// in	


//************************************************************************
//
//			P R O F I L E R		M A N A G E R	R E Q U E S T S
//
//************************************************************************

#define	SSAPI_PROFILE_MANAGER_START						(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 1)
	#define	SSAPI_PROFILE_MANAGER_START_IOP_SLOT				0	// in (type: int)
	#define	SSAPI_PROFILE_MANAGER_START_INTERVAL				1	// in (microseconds, type: I64)

#define	SSAPI_PROFILE_MANAGER_STOP						(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 2)
	#define	SSAPI_PROFILE_MANAGER_STOP_IOP_SLOT					0	// in (type: int)

#define	SSAPI_PROFILE_MANAGER_CLEAR						(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 3)
	#define	SSAPI_PROFILE_MANAGER_CLEAR_IOP_SLOT				0	// in (type: int)

#define	SSAPI_PROFILE_MANAGER_DELIVER					(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 4)
	#define	SSAPI_PROFILE_MANAGER_DELIVER_IOP_SLOT				0	// in (type: int)
	#define	SSAPI_PROFILE_MANAGER_DELIVER_START_ADDRESS			1	// in (type: U32 )
	#define	SSAPI_PROFILE_MANAGER_DELIVER_BLOB					1	// out (type: GenericData )

#define	SSAPI_PROFILE_MANAGER_HEAP_CLEAR				(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 5)
	#define	SSAPI_PROFILE_MANAGER_HEAP_CLEAR_IOP_SLOT			0	// in (type: int)

#define	SSAPI_PROGILE_MANAGER_HEAP_DELIVER				(SSAPI_OBJECT_MANAGER_LAST_RESERVED_REQUEST + 6)
	#define	SSAPI_PROGILE_MANAGER_HEAP_DELIVER_IOP_SLOT			0	// in (type: int)
	#define	SSAPI_PROGILE_MANAGER_HEAP_DELIVER_START_ADDRESS	1	// in (type: U32)
	#define	SSAPI_PROGILE_MANAGER_HEAP_DELIVER_BLOB				1	// out (type: GenericData)


//************************************************************************
//Managed Objects
//************************************************************************

#define	SSAPI_OBJECT_CLASS_TYPE_USER						1
#define SSAPI_OBJECT_CLASS_TYPE_PHS_DATA					31
	#define SSAPI_OBJECT_CLASS_TYPE_PHS_DATA_INT				2
	#define	SSAPI_OBJECT_CLASS_TYPE_PHS_DATA_FLOAT				3
	#define	SSAPI_OBJECT_CLASS_TYPE_PHS_DATA_TEMPERATURE		4
	#define	SSAPI_OBJECT_CLASS_TYPE_PHS_DATA_TIME				5
	#define	SSAPI_OBJECT_CLASS_TYPE_PHS_DATA_INT64				27	
	#define SSAPI_OBJECT_CLASS_TYPE_PHS_DATA_THROUGHPUT			51
	#define SSAPI_OBJECT_CLASS_TYPE_PHS_DATA_VOLTAGE			49
	#define SSAPI_OBJECT_CLASS_TYPE_PHS_DATA_CURRENT			52		
#define	SSAPI_OBJECT_CLASS_TYPE_DEVICE						32
	#define	SSAPI_OBJECT_CLASS_TYPE_CORD_SET					86	
	#define SSAPI_OBJECT_CLASS_TYPE_FILLER_BOARD				6
		#define SSAPI_OBJECT_CLASS_TYPE_HBC_FILLER_BOARD			58	
	#define SSAPI_OBJECT_CLASS_TYPE_IOP							42
		#define SSAPI_OBJECT_CLASS_TYPE_HBC_BOARD					7
		#define SSAPI_OBJECT_CLASS_TYPE_SSD_BOARD					8
		#define	SSAPI_OBJECT_CLASS_TYPE_NAC_BOARD					9
			#define	SSAPI_OBJECT_CLASS_TYPE_SNAC_BOARD					76
	#define SSAPI_OBJECT_CLASS_TYPE_FAN							10
	#define	SSAPI_OBJECT_CLASS_TYPE_CHASSIS_POWER_SUPPLY		11
	#define	SSAPI_OBJECT_CLASS_TYPE_BUS_SEGMENT					12
	#define	SSAPI_OBJECT_CLASS_TYPE_BATTERY						13
	#define SSAPI_OBJECT_CLASS_TYPE_DEVICE_COLLECTION			14
		#define SSAPI_OBJECT_CLASS_TYPE_PCI_COLLECTION				46
		#define	SSAPI_OBJECT_CLASS_TYPE_FC_COLLECTION				47
		#define SSAPI_OBJECT_CLASS_TYPE_EVC_COLLECTION				48	
	#define SSAPI_OBJECT_CLASS_TYPE_PORT						57		
		#define SSAPI_OBJECT_CLASS_TYPE_FC_PORT						15
			#define SSAPI_OBJECT_CLASS_TYPE_INTERNAL_FC_PORT			77
	#define SSAPI_OBJECT_CLASS_TYPE_HDD_DEVICE					16
	#define SSAPI_OBJECT_CLASS_TYPE_DDH_DEVICE					17
	#define	SSAPI_OBJECT_CLASS_TYPE_DISK_POWER_SUPPLY			18
	#define SSAPI_OBJECT_CLASS_TYPE_CHASSIS						26
	#define SSAPI_OBJECT_CLASS_TYPE_BOARD						40
	#define SSAPI_OBJECT_CLASS_TYPE_POWER_SUPPLY				41		
#define SSAPI_OBJECT_CLASS_TYPE_ALARM						19
#define SSAPI_OBJECT_CLASS_TYPE_HOST						20
#define SSAPI_OBJECT_CLASS_TYPE_LOG_MESSAGE					21
#define SSAPI_OBJECT_CLASS_LOG_META_DATA					56  
#define SSAPI_OBJECT_CLASS_TYPE_LUN_MAP_ENTRY				22
#define SSAPI_OBJECT_CLASS_TYPE_PROCESS						23
	#define SSAPI_OBJECT_CLASS_TYPE_RAID_UTILITY				38
		#define	SSAPI_OBJECT_CLASS_TYPE_RAID_INITIALIZE				67
		#define	SSAPI_OBJECT_CLASS_TYPE_RAID_VERIFY					68
		#define	SSAPI_OBJECT_CLASS_TYPE_RAID_REGENERATE				69
		#define	SSAPI_OBJECT_CLASS_TYPE_RAID_SMART_COPY				70
		#define	SSAPI_OBJECT_CLASS_TYPE_RAID_HOT_COPY				71 
#define	SSAPI_OBJECT_CLASS_TYPE_STORAGE_ELEMENT_BASE		78	
	#define SSAPI_OBJECT_CLASS_TYPE_STORAGE_ELEMENT				24
		#define SSAPI_OBJECT_CLASS_TYPE_PARTITION_STORAGE_ELEMENT	33
		#define SSAPI_OBJECT_CLASS_TYPE_SSD_STORAGE_ELEMENT			62
		#define SSAPI_OBJECT_CLASS_TYPE_DISK_STORAGE_ELEMENT		25
			#define SSAPI_OBJECT_CLASS_TYPE_DISK_INTERNAL				74
			#define SSAPI_OBJECT_CLASS_TYPE_DISK_EXTERNAL				75	
		#define	SSAPI_OBJECT_CLASS_TYPE_ARRAY_STORAGE_ELEMENT		34
			#define SSAPI_OBJECT_CLASS_TYPE_ARRAY_0_STORAGE_ELEMENT		63
			#define SSAPI_OBJECT_CLASS_TYPE_ARRAY_1_STORAGE_ELEMENT		64	
				#define SSAPI_OBJECT_CLASS_TYPE_ARRAY_HOT_COPY				54
					#define SSAPI_OBJECT_CLASS_TYPE_ARRAY_HOT_COPY_AUTO			55
					#define SSAPI_OBJECT_CLASS_TYPE_ARRAY_HOT_COPY_MANUAL		73		
	#define SSAPI_OBJECT_CLASS_TYPE_STORAGE_COLLECTION			37
		#define SSAPI_OBJECT_CLASS_TYPE_STORAGE_COLL_SPARE_POOL		66 
	#define	SSAPI_OBJECT_CLASS_TYPE_STORAGE_ELEMENT_PASS_THRU	65
		#define	SSAPI_OBJECT_CLASS_TYPE_TAPE						35
		#define	SSAPI_OBJECT_CLASS_TYPE_SES							39
#define SSAPI_OBJECT_CLASS_TYPE_MANAGED_OBJECT				28
#define SSAPI_OBJECT_CLASS_TYPE_CAPABILITY					30
#define SSAPI_OBJECT_CLASS_TYPE_SOFTWARE_IMAGE				36
#define	SSAPI_OBJECT_CLASS_TYPE_SW_IMAGE_DESCRIPTOR			29
	#define	SSAPI_OBJECT_CLASS_TYPE_IOP_SW_IMAGE_DESCRIPTOR		79
		#define	SSAPI_OBJECT_CLASS_TYPE_NAC_SW_IMAGE_DESCRIPTOR		80
		#define	SSAPI_OBJECT_CLASS_TYPE_HBC_SW_IMAGE_DESCRIPTOR		81
		#define	SSAPI_OBJECT_CLASS_TYPE_SSD_SW_IMAGE_DESCRIPTOR		82
#define SSAPI_OBJECT_CLASS_TYPE_POWERABLE_INTERFACE			43	
#define SSAPI_OBJECT_CLASS_TYPE_SERVICEABLE_INTERFACE		44	
#define SSAPI_OBJECT_CLASS_TYPE_LOCKABLE_INTERFACE			45
#define SSAPI_OBJECT_CLASS_TYPE_DATA_PATH					50
	#define SSAPI_OBJECT_CLASS_TYPE_REDUNDANT_DATA_PATH			53	
	#define SSAPI_OBJECT_CLASS_TYPE_CLUSTERED_DATA_PATH			87	// <-- the last
#define SSAPI_OBJECT_CLASS_TYPE_CONNECTION					59
	#define	SSAPI_OBJECT_CLASS_TYPE_UPSTREAM_CONNECTION			60
	#define SSAPI_OBJECT_CLASS_TYPE_DOWNSTREAM_CONNECTION		61
#define	SSAPI_OBJECT_CLASS_TYPE_CONFIG_ID					72 
#define	SSAPI_OBJECT_CLASS_TYPE_TABLE_META_DATA				83
#define	SSAPI_OBJECT_CLASS_TYPE_PTS_TABLE					84
#define	SSAPI_OBJECT_CLASS_TYPE_PTS_TABLE_ROW				85	



//************************************************************************
//	Managed Object (and derived) memebers
//************************************************************************

//Managed Object field ids

#define	SSAPI_OBJECT_FID_OBJECT_CLASS_TYPE			0
#define	SSAPI_OBJECT_FID_PARENTS_ID_VECTOR			1
#define	SSAPI_OBJECT_FID_ID							2
#define	SSAPI_OBJECT_FID_CHILDREN_ID_VECTOR			3
#define SSAPI_OBJECT_FID_MANAGER_CLASS_TYPE			4
#define	SSAPI_OBJECT_FID_PHSDATA_ID_VECTOR			5

//global interfaces
#define SSAPI_OBJECT_FID_IS_POWERED					6
#define SSAPI_OBJECT_FID_IS_LOCKED					7
#define SSAPI_OBJECT_FID_SERVICE_STATE				8
#define	SSAPI_OBJECT_FID_STATE						9
#define SSAPI_OBJECT_FID_STATE_STRING				10
#define	SSAPI_OBJECT_FID_ASSET_TAG_OBJECT			11

#define SSAPI_OBJECT_LAST_FID						SSAPI_OBJECT_FID_ASSET_TAG_OBJECT // must be bumped up/down on a change

//USER object field ids
#define SSAPI_USER_FID_USERNAME						(SSAPI_OBJECT_LAST_FID + 1)
#define SSAPI_USER_FID_PASSWORD						(SSAPI_OBJECT_LAST_FID + 2)
#define SSAPI_USER_FID_FIRST_NAME					(SSAPI_OBJECT_LAST_FID + 3)
#define SSAPI_USER_FID_LAST_NAME					(SSAPI_OBJECT_LAST_FID + 4)
#define SSAPI_USER_FID_DESCRIPTION					(SSAPI_OBJECT_LAST_FID + 5)
#define SSAPI_USER_FID_EMAIL						(SSAPI_OBJECT_LAST_FID + 6)
#define SSAPI_USER_FID_LANGUAGE						(SSAPI_OBJECT_LAST_FID + 7)
#define SSAPI_USER_FID_PHONE_1						(SSAPI_OBJECT_LAST_FID + 8)
#define SSAPI_USER_FID_PHONE_2						(SSAPI_OBJECT_LAST_FID + 9)
#define SSAPI_USER_FID_DEPARTMENT					(SSAPI_OBJECT_LAST_FID + 10)


// PHSData field ids
#define	SSAPI_PHS_FID_HAS_NON_CRIT_THRESHOLD		(SSAPI_OBJECT_LAST_FID + 1)
#define SSAPI_PHS_FID_HAS_CRIT_THRESHOLD			(SSAPI_OBJECT_LAST_FID + 2)	
#define	SSAPI_PHS_FID_HAS_FATAL_THRESHOLD			(SSAPI_OBJECT_LAST_FID + 3)
#define	SSAPI_PHS_FID_IS_SETTABLE					(SSAPI_OBJECT_LAST_FID + 4)
#define	SSAPI_PHS_FID_NAME							(SSAPI_OBJECT_LAST_FID + 5)
#define SSAPI_PHS_FID_HAS_SAMPLE_RATE				(SSAPI_OBJECT_LAST_FID + 6)
#define	SSAPI_PHS_FID_SAMPLE_RATE					(SSAPI_OBJECT_LAST_FID + 7)
#define SSAPI_PHS_FID_VALUE_TYPE					(SSAPI_OBJECT_LAST_FID + 8)
#define SSAPI_PHS_FID_COLLECTION_TIMESTAMP			(SSAPI_OBJECT_LAST_FID + 9)
#define SSAPI_PHS_DATA_LAST_FID						SSAPI_PHS_FID_COLLECTION_TIMESTAMP		// must be bumped up/down on a change


// PHSDataInt, PHSDataFloat, PHSDataTemperature, PHSDataTime, PHSDataInt64 field ids
#define	SSAPI_PHS_INT_FLOAT_FID_VALUE				(SSAPI_PHS_DATA_LAST_FID + 1)
#define	SSAPI_PHS_INT_FLOAT_FID_CRIT_THRESHOLD		(SSAPI_PHS_DATA_LAST_FID + 2)
#define	SSAPI_PHS_INT_FLOAT_FID_FATAL_THRESHOLD		(SSAPI_PHS_DATA_LAST_FID + 3)
#define SSAPI_PHS_INT_FLOAT_FID_NON_CRIT_THRESHOLD	(SSAPI_PHS_DATA_LAST_FID + 4)

// Device field ids
#define SSAPI_DEVICE_FID_NAME						(SSAPI_OBJECT_LAST_FID + 1)
#define SSAPI_DEVICE_FID_MICROCONTROLLER_VECTOR		(SSAPI_OBJECT_LAST_FID + 2)
#define	SSAPI_DEVICE_FID_LOCATION					(SSAPI_OBJECT_LAST_FID + 3)
#define SSAPI_DEVICE_LAST_FID						SSAPI_DEVICE_FID_LOCATION		// must be bumped up/down on a change

// Board field ids
#define SSAPI_BOARD_FID_SLOT						(SSAPI_DEVICE_LAST_FID + 1)
#define SSAPI_BOARD_FID_SLOT_NAME					(SSAPI_DEVICE_LAST_FID + 2)
#define SSAPI_BOARD_LAST_FID						SSAPI_BOARD_FID_SLOT_NAME // must be bumped up/down on a change

// IOP field ids
#define SSAPI_IOP_FID_REDUNDANT_SLOT				(SSAPI_BOARD_LAST_FID + 1)
#define SSAPI_IOP_FID_HW_VERSION					(SSAPI_BOARD_LAST_FID + 2)
#define SSAPI_IOP_FID_MANUFACTURER					(SSAPI_BOARD_LAST_FID + 3)
#define SSAPI_IOP_FID_SERIAL_NUMBER					(SSAPI_BOARD_LAST_FID + 4)	
#define SSAPI_IOP_FID_IOP_NAME						(SSAPI_BOARD_LAST_FID + 5)
#define SSAPI_IOP_LAST_FID							SSAPI_IOP_FID_IOP_NAME // must be bumped up/down on a change	

// Fan field ids
#define	SSAPI_FAN_FID_SPEED							(SSAPI_DEVICE_LAST_FID + 1)

// Chassis Power Supply field ids
#define SSAPI_CHASSIS_PS_FID_INPUT_OK				(SSAPI_DEVICE_LAST_FID + 1)
#define SSAPI_CHASSIS_PS_FID_OUTPUT_OK				(SSAPI_DEVICE_LAST_FID + 2)

//HDD field ids
#define SSAPI_HDD_FID_BAY_NUMBER					(SSAPI_DEVICE_LAST_FID + 1)
#define	SSAPI_HDD_FID_TARGET_ID						(SSAPI_DEVICE_LAST_FID + 2)
#define SSAPI_HDD_FID_SERIAL_NUMBER					(SSAPI_DEVICE_LAST_FID + 3)
#define SSAPI_HDD_FID_CAPACITY						(SSAPI_DEVICE_LAST_FID + 4)
#define SSAPI_HDD_FID_STATUS						(SSAPI_DEVICE_LAST_FID + 5)

// DDH field Ids
#define	SSAPI_DDH_FID_MANUFACTURER					(SSAPI_DEVICE_LAST_FID + 1)
#define	SSAPI_DDH_FID_HW_PART_NO					(SSAPI_DEVICE_LAST_FID + 2)
#define SSAPI_DDH_FID_HW_REVISION					(SSAPI_DEVICE_LAST_FID + 3)
#define SSAPI_DDH_FID_HW_MFG_DATE					(SSAPI_DEVICE_LAST_FID + 4)

//FCPort field ids
#define	SSAPI_FC_PORT_FID_PORT_NUMBER				(SSAPI_DEVICE_LAST_FID + 1)
#define SSAPI_FC_PORT_FID_CHIP_NUMBER				(SSAPI_DEVICE_LAST_FID + 2)
#define SSAPI_FC_PORT_FID_CHIP_NAME					(SSAPI_DEVICE_LAST_FID + 3)

//Chassis field ids
#define SSAPI_CHASSIS_FID_NUM_SLOTS					(SSAPI_DEVICE_LAST_FID + 1)
#define SSAPI_CHASSIS_FID_NUM_BUS_SEGMENTS			(SSAPI_DEVICE_LAST_FID + 2)
#define SSAPI_CHASSIS_FID_NUM_BAYS					(SSAPI_DEVICE_LAST_FID + 3)
#define	SSAPI_CHASSIS_FID_SSAPI_MINOR_VERSION		(SSAPI_DEVICE_LAST_FID + 4)
#define	SSAPI_CHASSIS_FID_SSAPI_MAJOR_VERSION		(SSAPI_DEVICE_LAST_FID + 5)
#define SSAPI_CHASSIS_FID_KEY_POSITION				(SSAPI_DEVICE_LAST_FID + 6)
#define	SSAPI_CHASSIS_FID_SERIAL_NUMBER				(SSAPI_DEVICE_LAST_FID + 7)
#define	SSAPI_CHASSIS_FID_IP_ADDRESS				(SSAPI_DEVICE_LAST_FID + 8)
#define	SSAPI_CHASSIS_FID_SUBNET_MASK				(SSAPI_DEVICE_LAST_FID + 9)
#define	SSAPI_CHASSIS_FID_HOST_NAME					(SSAPI_DEVICE_LAST_FID + 10)
#define	SSAPI_CHASSIS_FID_LOCATION					(SSAPI_DEVICE_LAST_FID + 11)
#define	SSAPI_CHASSIS_FID_GMT_TIME_BASE				(SSAPI_DEVICE_LAST_FID + 12)				
#define	SSAPI_CHASSIS_FID_TRAP_IP_ADDRESS_VECTOR	(SSAPI_DEVICE_LAST_FID + 13)
#define	SSAPI_CHASSIS_FID_GATEWAY					(SSAPI_DEVICE_LAST_FID + 14)

// Battery object codes
#define	SSAPI_BATTERY_FID_IS_PRESENT				(SSAPI_DEVICE_LAST_FID + 1)
#define SSAPI_BATTERY_FID_IS_FUSE_1_OK				(SSAPI_DEVICE_LAST_FID + 2)
#define SSAPI_BATTERY_FID_IS_FUSE_2_OK				(SSAPI_DEVICE_LAST_FID + 3)
#define SSAPI_BATTERY_FID_CURRENT					(SSAPI_DEVICE_LAST_FID + 4)

//Port field ids
#define SSAPI_PORT_FID_UPSTREAM						(SSAPI_DEVICE_LAST_FID + 1)
#define SSAPI_PORT_FID_CAPACITY						(SSAPI_DEVICE_LAST_FID + 2)

//BusSegment field ids


//Alarm field ids
#define SSAPI_ALARM_FID_SEVERITY					(SSAPI_OBJECT_LAST_FID + 1)
#define SSAPI_ALARM_FID_SOURCE_OBJECT_ID			(SSAPI_OBJECT_LAST_FID + 2)
#define	SSAPI_ALARM_FID_SOURCE_OBJECT_MANAGER		(SSAPI_OBJECT_LAST_FID + 3)
#define SSAPI_ALARM_FID_MESSAGE_CODE				(SSAPI_OBJECT_LAST_FID + 4)
#define SSAPI_ALARM_FID_IS_CLEARABLE				(SSAPI_OBJECT_LAST_FID + 5)
#define SSAPI_ALARM_FID_IS_ACTIVE					(SSAPI_OBJECT_LAST_FID + 6)
#define SSAPI_ALARM_FID_IS_ACKNOWLEDGED				(SSAPI_OBJECT_LAST_FID + 7)
#define SSAPI_ALARM_FID_PARAMETER_VECTOR			(SSAPI_OBJECT_LAST_FID + 8)
#define	SSAPI_ALARM_FID_HISTORY_VECTOR				(SSAPI_OBJECT_LAST_FID + 9)


// Alarm History ids (not a MO!)
#define	SSAPI_ALARM_HISTORY_TIME_STAMP				1
#define	SSAPI_ALARM_HISTORY_ACTION_TYPE				2
#define	SSAPI_ALARM_HISTORY_USER_NAME				3
#define	SSAPI_ALARM_HISTORY_USER_NOTES				4

// AssetTag ids (not a MO!)
#define	SSAPI_ASSET_FID_SERIAL_NUMBER				1
#define	SSAPI_ASSET_FID_VERSION_NUMBER				2
#define	SSAPI_ASSET_FID_PRODUCTION_DATE				3

// MicroController ids (not a MO!)
#define	SSAPI_MICROCONTROLLER_FID_NAME				1
#define	SSAPI_MICROCONTROLLER_FID_HW_VERSION		2
#define	SSAPI_MICROCONTROLLER_FID_FW_VERSION		3

//Host field ids
#define SSAPI_HOST_FID_NAME							(SSAPI_OBJECT_LAST_FID + 1)
#define SSAPI_HOST_FID_DESCRIPTION					(SSAPI_OBJECT_LAST_FID + 2)
#define SSAPI_HOST_FID_OS							(SSAPI_OBJECT_LAST_FID + 3)
#define SSAPI_HOST_FID_IP_ADDRESS					(SSAPI_OBJECT_LAST_FID + 4)
#define	SSAPI_HOST_FID_CONNECTION_ID_VECTOR			(SSAPI_OBJECT_LAST_FID + 5)

// DataPath field ids
#define SSAPI_DATA_PATH_FID_DESCRIPTION				(SSAPI_OBJECT_LAST_FID + 1)
#define SSAPI_DATA_PATH_FID_NAME					(SSAPI_OBJECT_LAST_FID + 2)
#define SSAPI_DATA_PATH_LAST_FID					SSAPI_DATA_PATH_FID_NAME

// RedundantDataPath ids

// ExternalPort field ids
#define SSAPI_CONNECTION_FID_ID						(SSAPI_OBJECT_LAST_FID + 1)
#define SSAPI_CONNECTION_FID_WWNAME					(SSAPI_OBJECT_LAST_FID + 2)
#define SSAPI_CONNECTION_FID_GEMINI_PORT_ID			(SSAPI_OBJECT_LAST_FID + 3)
#define SSAPI_CONNECTION_FID_NAME					(SSAPI_OBJECT_LAST_FID + 4)

//LogMessage field ids
#define SSAPI_LOG_MESSAGE_FID_TIME_STAMP			(SSAPI_OBJECT_LAST_FID + 1)
#define SSAPI_LOG_MESSAGE_FID_SEVERITY				(SSAPI_OBJECT_LAST_FID + 2)
#define SSAPI_LOG_MESSAGE_FID_EVENT_CODE			(SSAPI_OBJECT_LAST_FID + 3)
#define SSAPI_LOG_MESSAGE_FID_FACILITY				(SSAPI_OBJECT_LAST_FID + 4)
#define SSAPI_LOG_MESSAGE_FID_SLOT					(SSAPI_OBJECT_LAST_FID + 5)
#define SSAPI_LOG_MESSAGE_FID_SEQ_NUMBER			(SSAPI_OBJECT_LAST_FID + 6)
#define SSAPI_LOG_MESSAGE_FID_DID					(SSAPI_OBJECT_LAST_FID + 7)
#define SSAPI_LOG_MESSAGE_FID_VDN					(SSAPI_OBJECT_LAST_FID + 8)
#define	SSAPI_LOG_MESSAGE_FID_PARAMETER_VECTOR		(SSAPI_OBJECT_LAST_FID + 9)

//LUNMapEntry field ids
#define SSAPI_LUN_MAP_ENTRY_FID_VERIFIED			(SSAPI_OBJECT_LAST_FID + 1)
#define SSAPI_LUN_MAP_ENTRY_FID_EXPORTED			(SSAPI_OBJECT_LAST_FID + 2)
// + 3 can be re-used!
#define SSAPI_LUN_MAP_ENTRY_FID_USES_CACHE			(SSAPI_OBJECT_LAST_FID + 4)
#define SSAPI_LUN_MAP_ENTRY_FID_ID_INFO_OBJECT		(SSAPI_OBJECT_LAST_FID + 5)
#define SSAPI_LUN_MAP_ENTRY_FID_DESCRIPTION			(SSAPI_OBJECT_LAST_FID + 6)
#define SSAPI_LUN_MAP_ENTRY_FID_HC_ID				(SSAPI_OBJECT_LAST_FID + 7)
#define	SSAPI_LUN_MAP_ENTRY_FID_STORAGE_ELEMENT_ID	(SSAPI_OBJECT_LAST_FID + 8)
#define SSAPI_LUN_MAP_ENTRY_FID_PROTOCOL_TYPE		(SSAPI_OBJECT_LAST_FID + 9)
#define	SSAPI_LUN_MAP_ENTRY_FID_NAME				(SSAPI_OBJECT_LAST_FID + 10)

//Process field ids
#define SSAPI_PROCESS_FID_CAN_START					(SSAPI_OBJECT_LAST_FID + 1)
#define SSAPI_PROCESS_FID_CAN_ABORT					(SSAPI_OBJECT_LAST_FID + 2)
#define SSAPI_PROCESS_FID_CAN_PAUSE					(SSAPI_OBJECT_LAST_FID + 3)
#define SSAPI_PROCESS_FID_PERCENT_COMPLETE			(SSAPI_OBJECT_LAST_FID + 4)
#define SSAPI_PROCESS_FID_PRIORITY					(SSAPI_OBJECT_LAST_FID + 5)
#define SSAPI_PROCESS_FID_TIME_STARTED				(SSAPI_OBJECT_LAST_FID + 6)
#define SSAPI_PROCESS_FID_STATE						(SSAPI_OBJECT_LAST_FID + 7)
#define SSAPI_PROCESS_FID_NAME						(SSAPI_OBJECT_LAST_FID + 8)
#define SSAPI_PROCESS_FID_OWNER_ID					(SSAPI_OBJECT_LAST_FID + 9)
#define SSAPI_PROCESS_FID_OWNER_MANAGER_CLASS_TYPE	(SSAPI_OBJECT_LAST_FID + 10)
#define SSAPI_PROCESS_FID_LAST						SSAPI_PROCESS_FID_OWNER_MANAGER_CLASS_TYPE


// StorageIdInfo ids (not a MO!)
#define	SSAPI_STORAGE_ID_INFO_FID_VENDOR				0
#define	SSAPI_STORAGE_ID_INFO_FID_PRODUCT				1
#define	SSAPI_STORAGE_ID_INFO_FID_REVISION				2
#define	SSAPI_STORAGE_ID_INFO_FID_SERIAL_NUMBER			3
#define	SSAPI_STORAGE_ID_INFO_FID_WWNAME				4
#define	SSAPI_STORAGE_ID_INFO_FID_TARGET_ID				5
#define	SSAPI_STORAGE_ID_INFO_FID_TARGET_LUN			6

//StorageElementBase field ids
#define SSAPI_STORAGE_ELEMENT_B_FID_CAPACITY			(SSAPI_OBJECT_LAST_FID + 1)
#define SSAPI_STORAGE_ELEMENT_B_FID_IN_USE				(SSAPI_OBJECT_LAST_FID + 2)
#define SSAPI_STORAGE_ELEMENT_B_FID_NAME				(SSAPI_OBJECT_LAST_FID + 3)
#define SSAPI_STORAGE_ELEMENT_B_FID_CAN_BE_DELETED		(SSAPI_OBJECT_LAST_FID + 4)
#define SSAPI_STORAGE_ELEMENT_B_FID_IS_SPARE			(SSAPI_OBJECT_LAST_FID + 5)
#define	SSAPI_STORAGE_ELEMENT_B_FID_IS_EXPORTABLE		(SSAPI_OBJECT_LAST_FID + 6)
#define	SSAPI_STORAGE_ELEMENT_B_FID_DEVICE_ID_VECTOR	(SSAPI_OBJECT_LAST_FID + 7)
#define SSAPI_STORAGE_ELEMENT_B_FID_ID_INFO_OBJECT		(SSAPI_OBJECT_LAST_FID + 8)
#define SSAPI_STORAGE_ELEMENT_B_FID_LAST				SSAPI_STORAGE_ELEMENT_B_FID_ID_INFO_OBJECT


#define	SSAPI_STORAGE_ELEMENT_FID_LAST					SSAPI_STORAGE_ELEMENT_B_FID_LAST			
//DiskStorageElement field ids


// StorageElementArray
#define	SSAPI_STORAGE_ELEMENT_ARRAY_FID_MEMBER_CAPACITY		(SSAPI_STORAGE_ELEMENT_FID_LAST + 1)
#define	SSAPI_STORAGE_ELEMENT_ARRAY_FID_DATA_BLOCK_SIZE		(SSAPI_STORAGE_ELEMENT_FID_LAST + 2)
#define	SSAPI_STORAGE_ELEMENT_ARRAY_FID_PARITY_BLOCK_SIZE	(SSAPI_STORAGE_ELEMENT_FID_LAST + 3)
#define	SSAPI_STORAGE_ELEMENT_ARRAY_FID_PECKING_ORDER		(SSAPI_STORAGE_ELEMENT_FID_LAST + 4)
#define	SSAPI_STORAGE_ELEMENT_ARRAY_FID_IS_INITED			(SSAPI_STORAGE_ELEMENT_FID_LAST + 5)
#define	SSAPI_STORAGE_ELEMENT_ARRAY_FID_SERIAL_NUMBER		(SSAPI_STORAGE_ELEMENT_FID_LAST + 6)
#define	SSAPI_STORAGE_ELEMENT_ARRAY_FID_CREATION_TIME		(SSAPI_STORAGE_ELEMENT_FID_LAST + 7)
#define	SSAPI_STORAGE_ELEMENT_ARRAY_FID_HOST_SPAREPOOL_ID	(SSAPI_STORAGE_ELEMENT_FID_LAST + 8)
#define SSAPI_STORAGE_ELEMENT_ARRAY_FID_LAST				SSAPI_STORAGE_ELEMENT_ARRAY_FID_HOST_SPAREPOOL_ID

// StorageElementArray1
#define	SSAPI_STORAGE_ELEMENT_ARRAY1_FID_PREF_MEMBER_ID		(SSAPI_STORAGE_ELEMENT_ARRAY_FID_LAST + 1)
#define SSAPI_STORAGE_ELEMENT_ARRAY1_FID_SOURCE_MEMBER_ID	(SSAPI_STORAGE_ELEMENT_ARRAY_FID_LAST + 2)


// StorageCollection field ids
#define SSAPI_STORAGE_COLLECTION_FID_LAST					SSAPI_STORAGE_ELEMENT_B_FID_LAST

// StorageCollectionSparePool field ids
#define SSAPI_STORAGE_COLL_SPAREPOOL_FID_HOST_ID			(SSAPI_STORAGE_COLLECTION_FID_LAST + 1)	

// StoragreElementPartition field ids
#define	SSAPI_PARTITION_STORAGE_ELEMENT_FID_OWNER_ID		(SSAPI_STORAGE_ELEMENT_FID_LAST + 1)
#define	SSAPI_PARTITION_STORAGE_ELEMENT_FID_PREV_ID			(SSAPI_STORAGE_ELEMENT_FID_LAST + 2)
#define	SSAPI_PARTITION_STORAGE_ELEMENT_FID_NEXT_ID			(SSAPI_STORAGE_ELEMENT_FID_LAST + 3)

// ConfigId field ids
#define	SSAPI_CONFIG_ID_FID_CONFIG_STAMP					(SSAPI_OBJECT_LAST_FID + 1)		

// LogMetaData field ids
#define	SSAPI_LOG_META_DATA_FID_FIRST_SEQ_NUMBER_VECTOR		(SSAPI_OBJECT_LAST_FID + 1)
#define	SSAPI_LOG_META_DATA_FID_LAST_SEQ_NUMBER_VECTOR		(SSAPI_OBJECT_LAST_FID + 2)
#define	SSAPI_LOG_META_DATA_FID_MESSAGE_COUNT_VECTOR		(SSAPI_OBJECT_LAST_FID + 3)

// SW image descriptor Ids
#define	SSAPI_SW_IMAGE_DESCRIPTOR_FID_LAST					SSAPI_OBJECT_LAST_FID

// IOP SW image descriptor ids
#define	SSAPI_IOP_SW_IMAGE_DESCRIPTOR_FID_MAJOR_VERSION		(SSAPI_SW_IMAGE_DESCRIPTOR_FID_LAST + 1)
#define	SSAPI_IOP_SW_IMAGE_DESCRIPTOR_FID_MINOR_VERSION		(SSAPI_SW_IMAGE_DESCRIPTOR_FID_LAST + 2)
#define	SSAPI_IOP_SW_IMAGE_DESCRIPTOR_FID_LOADED_ON			(SSAPI_SW_IMAGE_DESCRIPTOR_FID_LAST + 3)
#define	SSAPI_IOP_SW_IMAGE_DESCRIPTOR_FID_REFERENCE_COUNT	(SSAPI_SW_IMAGE_DESCRIPTOR_FID_LAST + 4)
#define	SSAPI_IOP_SW_IMAGE_DESCRIPTOR_FID_IS_DEFAULT		(SSAPI_SW_IMAGE_DESCRIPTOR_FID_LAST + 5)

// SW image ids
#define	SSAPI_SOFTWARE_IMAGE_FID_DESCRIPTOR_OBJECT_ID		(SSAPI_OBJECT_LAST_FID + 1)
#define	SSAPI_SOFTWARE_IMAGE_FID_DEVICE_OBJECT_ID			(SSAPI_OBJECT_LAST_FID + 2)
#define	SSAPI_SOFTWARE_IMAGE_FID_IS_ACCEPTED				(SSAPI_OBJECT_LAST_FID + 3)
#define	SSAPI_SOFTWARE_IMAGE_FID_IS_CURRENT					(SSAPI_OBJECT_LAST_FID + 4)
#define	SSAPI_SOFTWARE_IMAGE_FID_LAST_BOOTED_TIMESTAMP		(SSAPI_OBJECT_LAST_FID + 5)
#define	SSAPI_SOFTWARE_IMAGE_FID_IS_PRIMARY					(SSAPI_OBJECT_LAST_FID + 6)

// PTS Meta Data ids
#define	SSAPI_TABLE_META_DATA_FID_TABLE_INFO_VECTOR			(SSAPI_OBJECT_LAST_FID + 1)

// table info ids ( not a MO!! )
#define	SSAPI_TABLE_INFO_FID_NAME							0
#define	SSAPI_TABLE_INFO_FID_ID								1

// Pts table ids
#define	SSAPI_PTS_TABLE_FID_FIELD_DEF_VECTOR				(SSAPI_OBJECT_LAST_FID + 1)

// Pts table row ids
#define	SSAPI_TABLE_ROW_FID_VALUE_VECTOR					(SSAPI_OBJECT_LAST_FID + 1)

//************************************************************************
//
//				P R O C E S S		S T A T E S
//
//************************************************************************

#define	SSAPI_PROCESS_STATE_RUNNING							1
#define	SSAPI_PROCESS_STATE_PAUSED							2
#define	SSAPI_PROCESS_STATE_ABORTED_BY_USER					3	
#define	SSAPI_PROCESS_STATE_ABORTED_IO_ERROR				4
#define	SSAPI_PROCESS_STATE_COMPLETE						5

#define SSAPI_PROCESS_PRIORITY_LOW							3
#define SSAPI_PROCESS_PRIORITY_MEDIUM						6
#define SSAPI_PROCESS_PRIORITY_HIGH							9



//************************************************************************
//
//
//						E V E N T			I D s
//
//
//************************************************************************

// EVENT codes
#define	SSAPI_EVENT_OBJECT_ADDED								1
#define	SSAPI_EVENT_OBJECT_DELETED								2
#define	SSAPI_EVENT_OBJECT_MODIFIED								3
#define	SSAPI_EVENT_CHILD_ADDED									4
#define	SSAPI_EVENT_CHILD_DELETED								5

// EVENT object field IDs
#define	SSAPI_EVENT_FID_EVENT_TYPE								1		
#define	SSAPI_EVENT_FID_TIMESTAMP								2
#define	SSAPI_EVENT_FID_MANAGED_OBJECT							3
#define SSAPI_EVENT_FID_PARENT_ID								4	// for child-related events



//************************************************************************
//
//
//			S S A P I		L I S T E N E R		T Y P E S
//						( it's a bit-mask )
// 
//************************************************************************

#define SSAPI_LISTENER_TYPE_OBJECT_ADDED						1
#define	SSAPI_LISTENER_TYPE_OBJECT_DELETED						2
#define	SSAPI_LISTENER_TYPE_CHILD_ADDED							4
#define	SSAPI_LISTENER_TYPE_CHILD_DELETED						8
#define	SSAPI_LISTENER_TYPE_OBJECT_MODIFIED						16


//************************************************************************
//
//
//			S S A P I		F I L T E R		T Y P E S
//
// 
//************************************************************************

#define	SSAPI_FILTER_CLASS_TYPE_INT_VECTOR						1		// I64/int is used
#define	SSAPI_FILTER_CLASS_TYPE_FLOAT_VECTOR					2
#define	SSAPI_FILTER_CLASS_TYPE_COUNT							3
#define	SSAPI_FILTER_CLASS_TYPE_DESIGNATOR_ID					4
#define SSAPI_FILTER_CLASS_TYPE_OBJECT_CLASS_TYPE				5


//************************************************************************
// Filter (base class) field ids
//************************************************************************
#define SSAPI_FILTER_FID_FILTER_CLASS_TYPE						1
#define SSAPI_FILTER_LAST_FID									SSAPI_FILTER_FID_FILTER_CLASS_TYPE

//************************************************************************
// IntVectorFilter, FloatVectorFilter, DesignatorIdVectorFilter field Ids
//************************************************************************
#define SSAPI_INT_FLOAT_VECTOR_FILTER_FID_COMPARATOR_TYPE		(SSAPI_FILTER_LAST_FID + 1)
#define SSAPI_INT_FLOAT_VECTOR_FILTER_FID_VALUE_VECTOR			(SSAPI_FILTER_LAST_FID + 2)
#define SSAPI_INT_FLOAT_VECTOR_FILTER_FID_FIELD_ID				(SSAPI_FILTER_LAST_FID + 3)

//************************************************************************
// CountFilter field Ids
//************************************************************************
#define SSAPI_COUNT_FILTER_MAX_COUNT							(SSAPI_FILTER_LAST_FID + 1)


//************************************************************************
// ObjectClassTypeFilter field Ids
//************************************************************************

#define SSAPI_OBJECT_CLASS_TYPE_FILTER_INCLUDE_DERIVATIONS		(SSAPI_FILTER_LAST_FID + 1)
#define SSAPI_OBJECT_CLASS_TYPE_FILTER_OBJECT_CLASS_TYPE		(SSAPI_FILTER_LAST_FID + 2)


//************************************************************************
// Comparator value defintions
//************************************************************************
#define	SSAPI_COMPARATOR_EQUAL									1
#define SSAPI_COMPARATOR_NOT_EQUAL								2
#define SSAPI_COMPARATOR_LESS_THAN_OR_EQUAL						3
#define SSAPI_COMPARATOR_LESS_THAN								4
#define SSAPI_COMPARATOR_GREATER_THAN_OR_EQUAL					5
#define SSAPI_COMPARATOR_GREATER_THAN							6


//************************************************************************
// Value Types for PHSData items
//************************************************************************

#define	SSAPI_PHS_DATA_VALUE_TYPE_COUNTER						1
#define	SSAPI_PHS_DATA_VALUE_TYPE_DELTA							2
#define	SSAPI_PHS_DATA_VALUE_TYPE_SNAPSHOT						3
#define	SSAPI_PHS_DATA_VALUE_TYPE_RATIO							4

//************************************************************************
// RAID pecking order
//************************************************************************

#define SSAPI_RAID_PECKING_ORDER_PECK_FIRST						1
#define SSAPI_RAID_PECKING_ORDER_PECK_LAST						2
#define SSAPI_RAID_PECKING_ORDER_NEVER_PECK						3


//************************************************************************
// Host Connection Modes
//************************************************************************

#define	SSAPI_HC_MODE_NON_REDUNDANT								0
#define	SSAPI_HC_MODE_ACTIVE_PASSIVE							1
#define	SSAPI_HC_MODE_MULTIPLE_READERS							2
#define	SSAPI_HC_MODE_ONE_WRITER								3
#define	SSAPI_HC_MODE_TWO_WRITERS								4
#define	SSAPI_HC_MODE_MULTIPLE_WRITERS							5
#define	SSAPI_HC_MODE_TRUSTED_WRITERS							6
#define	SSAPI_HC_MODE_COHERENT_CHACHE							7

//************************************************************************
// Individual Connection Modes
//************************************************************************

#define	SSAPI_CONNECTION_MODE_MASK_READER						1	// bit mask
#define	SSAPI_CONNECTION_MODE_MASK_WRITER						2	// bit mask


//************************************************************************
// Alarm History Action Types
//************************************************************************

#define	SSAPI_ALARM_HISTORY_ACTION_TYPE_ALARM_CREATED			1
#define	SSAPI_ALARM_HISTORY_ACTION_TYPE_ALARM_ACKNOWLEDGED		2
#define	SSAPI_ALARM_HISTORY_ACTION_TYPE_ALARM_UNACKNOWLEDGED	3 
#define	SSAPI_ALARM_HISTORY_ACTION_TYPE_ALARM_CLEARED			4
#define	SSAPI_ALARM_HISTORY_ACTION_TYPE_ALARM_NOTED				5

//************************************************************************
// Alarm Severities
//************************************************************************
#define SSAPI_ALARM_SEVERITY_CRITICAL							0
#define SSAPI_ALARM_SEVERITY_MINOR								1
#define SSAPI_ALARM_SEVERITY_WARNING							2


//************************************************************************
// Chassis Key Switch Positions
//************************************************************************

#define	SSAPI_CHASSIS_KEY_POSITION_OFF			0
#define	SSAPI_CHASSIS_KEY_POSITION_SERVICE		1
#define	SSAPI_CHASSIS_KEY_POSITION_SECURITY		2
#define	SSAPI_CHASSIS_KEY_POSITION_ON			3


#endif // _SSAPI_CODES_H__