/*************************************************************************/
/*                                                                       */
/*        Copyright (c) 1998      Accelerated Technology, Inc.           */
/*                                                                       */
/* PROPRIETARY RIGHTS of Accelerated Technology are involved in the      */
/* subject matter of this material.  All manufacturing, reproduction,    */
/* use, and sales rights pertaining to this subject matter are governed  */
/* by the license agreement.  The recipient of this software implicitly  */
/* accepts the terms of the license.                                     */
/*                                                                       */
/*************************************************************************/

/*************************************************************************/
/*                                                                       */
/* FILE NAME                                            VERSION          */
/*                                                                       */
/*      urt_defs.h                                      PPP   1.1        */
/*                                                                       */
/* COMPONENT                                                             */
/*                                                                       */
/*      UART                                                             */
/*                                                                       */
/* DESCRIPTION                                                           */
/*                                                                       */
/*      This file contains constant definitions for the UART  module     */
/*      of PPP.                                                          */
/*                                                                       */
/* AUTHOR                                                                */
/*                                                                       */
/*      Glen Johnson,     Accelerated Technology, Inc.                   */
/*                                                                       */
/* DATA STRUCTURES                                                       */
/*                                                                       */
/*      UART_REGS         A structure that maps the UART registers.      */
/*      _PPP_INIT_STRUCT  Uart initialization structure.                 */
/*                                                                       */
/* DEPENDENCIES                                                          */
/*                                                                       */
/*      none                                                             */
/*                                                                       */
/* HISTORY                                                               */
/*                                                                       */
/*      NAME            DATE            REMARKS                          */
/*      George Clark    01/26/98        Updated for ARM                  */
/*      S. Nguyen       02/20/98        For IDT4640 using UART 85C30     */
/*      S. Nguyen       08/26/98        Re-organized directory structure */
/*                                                                       */
/*************************************************************************/

/* Check to see if the file has been included already.  */

#ifndef URT_DEFS_H
#define URT_DEFS_H

#endif
