/*************************************************************************
 * This material is a confidential trade secret and proprietary 
 * information of ConvergeNet Technologies, Inc. which may not be 
 * reproduced, used, sold or transferred to any third party without the 
 * prior written consent of ConvergeNet Technologies, Inc.  This material 
 * is also copyrighted as an unpublished work under sections 104 and 408 
 * of Title 17 of the United States Code.  Law prohibits unauthorized 
 * use, copying or reproduction.
 *
 * File: galileo.h
 * 
 * Description:
 * This file contains register definition for Galileo GT-64XXX PCI controllers 
 * 
 * Update Log:
 * 10/16/98 Raghava Kondapalli: Merged TRK gt64120.h with this file 
 * XX/XX/98 Jeff Nespor:	Created
 * 11/11/98 Joe Altmaier:   Changed GTREG to avoid compiler bug.
 ************************************************************************/

#ifndef GALILEO_H
#define GALILEO_H

#ifndef HW_H
#include "hw.h"
#endif

/*
**
**	Galileo Register Offsets
**
*/
#define	GT_CPU_CONFIG_OFF		0x0000
#define GT_MULTI_GT_SUPPORT_OFF		0x0120


#define	GT_PROC_RAS10_LO_OFF		0x0008
#define	GT_PROC_RAS10_HI_OFF 		0x0010
#define	GT_PROC_RAS32_LO_OFF		0x0018
#define	GT_PROC_RAS32_HI_OFF 		0x0020
#define	GT_PROC_CS20_LO_OFF			0x0028
#define	GT_PROC_CS20_HI_OFF 		0x0030
#define	GT_PROC_CS3BOOTCS_LO_OFF	0x0038
#define	GT_PROC_CS3BOOTCS_HI_OFF 	0x0040
#define	GT_PROC_PCI_IO_LO_OFF		0x0048
#define	GT_PROC_PCI_IO_HI_OFF 		0x0050
#define	GT_PROC_PCI_MEM_LO_OFF		0x0058
#define	GT_PROC_PCI_MEM_HI_OFF 		0x0060
#define	GT_PROC_INT_SPACE_OFF 		0x0068
#define	GT_PROC_BUSERR_LO_OFF 		0x0070
#define	GT_PROC_BUSERR_HI_OFF 		0x0078
#define	GT_PROC_PCI0_MEM1_LO_OFF	0x0080
#define	GT_PROC_PCI0_MEM1_HI_OFF	0x0088
#define	GT_PROC_PCI_1_MEM_LO_OFF	0x00A0
#define	GT_PROC_PCI_1_MEM_HI_OFF 	0x00A8

#define	GT_DRAM_RAS0_LO_OFF			0x0400
#define	GT_DRAM_RAS0_HI_OFF			0x0404
#define	GT_DRAM_RAS1_LO_OFF			0x0408
#define	GT_DRAM_RAS1_HI_OFF			0x040C
#define	GT_DRAM_RAS2_LO_OFF			0x0410
#define	GT_DRAM_RAS2_HI_OFF			0x0414
#define	GT_DRAM_RAS3_LO_OFF			0x0418
#define	GT_DRAM_RAS3_HI_OFF			0x041C

#define	GT_DRAM_CS0_LO_OFF			0x0420
#define	GT_DRAM_CS0_HI_OFF			0x0424
#define	GT_DRAM_CS1_LO_OFF			0x0428
#define	GT_DRAM_CS1_HI_OFF			0x042C
#define	GT_DRAM_CS2_LO_OFF			0x0430
#define	GT_DRAM_CS2_HI_OFF			0x0434
#define	GT_DRAM_CS3_LO_OFF			0x0438
#define	GT_DRAM_CS3_HI_OFF			0x043C

#define	GT_DRAM_BOOTCS_LO_OFF			0x0440
#define	GT_DRAM_BOOTCS_HI_OFF			0x0444

#define	GT_DRAM_ADDRERR_OFF			0x0470

#define	GT_DRAM_CONFIG_OFF			0x0448
#define GT_DRAM_ADDR_DECODE_OFF			0x47c


#define	GT_DRAM0_PARMS_OFF			0x044C
#define	GT_DRAM1_PARMS_OFF			0x0450
#define	GT_DRAM2_PARMS_OFF			0x0454
#define	GT_DRAM3_PARMS_OFF			0x0458

#define	GT_DEV0_PARMS_OFF			0x045C
#define	GT_DEV1_PARMS_OFF			0x0460
#define	GT_DEV2_PARMS_OFF			0x0464
#define	GT_DEV3_PARMS_OFF			0x0468
#define GT_DRAM_OP_MODE_OFF			0x0474
#define GT_ADDR_DECODE_OFF			0x047C

#define	GT_DEV_BOOT_PARMS_OFF		0x046C

#define	GT_DMA_CH0_COUNT_OFF		0x0800
#define	GT_DMA_CH1_COUNT_OFF		0x0804
#define	GT_DMA_CH2_COUNT_OFF		0x0808
#define	GT_DMA_CH3_COUNT_OFF		0x080C

#define	GT_DMA_CH0_SRC_OFF			0x0810
#define	GT_DMA_CH1_SRC_OFF			0x0814
#define	GT_DMA_CH2_SRC_OFF			0x0818
#define	GT_DMA_CH3_SRC_OFF			0x081C

#define	GT_DMA_CH0_DEST_OFF			0x0820
#define	GT_DMA_CH1_DEST_OFF			0x0824
#define	GT_DMA_CH2_DEST_OFF			0x0828
#define	GT_DMA_CH3_DEST_OFF			0x082C

#define	GT_DMA_CH0_NEXT_OFF			0x0830
#define	GT_DMA_CH1_NEXT_OFF			0x0834
#define	GT_DMA_CH2_NEXT_OFF			0x0838
#define	GT_DMA_CH3_NEXT_OFF			0x083C

#define	GT_DMA_CH0_CONTROL_OFF		0x0840
#define	GT_DMA_CH1_CONTROL_OFF		0x0844
#define	GT_DMA_CH2_CONTROL_OFF		0x0848
#define	GT_DMA_CH3_CONTROL_OFF		0x084C

#define	GT_DMA_ARBITER_OFF			0x0860

#define	GT_TIMER0_OFF				0x0850
#define	GT_TIMER1_OFF				0x0854
#define	GT_TIMER2_OFF				0x0858
#define	GT_TIMER3_OFF				0x085C
#define	GT_TIMER_CONTROL_OFF		0x0864

#define	GT_PCI_COMMAND_OFF			0x0C00
#define	GT_PCI_RETRY_OFF			0x0C04
#define	GT_PCI_RAS10_BSIZE_OFF		0x0C08
#define	GT_PCI_RAS32_BSIZE_OFF		0x0C0C
#define	GT_PCI_CS20_BSIZE_OFF		0x0C10
#define	GT_PCI_BOOTCS_BSIZE_OFF		0x0C14
#define	GT_PCI_SERR_MASK_OFF		0x0C28
#define	GT_PCI_INT_ACK_OFF			0x0C34
#define	GT_PCI_RAS10_MAP_OFF		0x0C48
#define	GT_PCI_RAS32_MAP_OFF		0x0C4C
#define	GT_PCI_CONFIG_ADDR_OFF		0x0CF8
#define	GT_PCI_CONFIG_DATA_OFF		0x0CFC

#define	GT_INT_CAUSE_OFF			0x0C18
#define	GT_INT_CPU_MASK_OFF			0x0C1C
#define	GT_INT_PCI_MASK_OFF			0x0C24

#define	GT_PCICONF_DEVID_OFF		0x0000
#define	GT_PCICONF_STATCMD_OFF		0x0004
#define	GT_PCICONF_REVID_OFF		0x0008
#define	GT_PCICONF_HEADER_OFF		0x000C
#define	GT_PCICONF_RAS10_BASE_OFF	0x0010
#define	GT_PCICONF_RAS32_BASE_OFF	0x0014
#define	GT_PCICONF_CS20_BASE_OFF	0x0018
#define	GT_PCICONF_BOOTCS_BASE_OFF	0x001C
#define	GT_PCICONF_MEMMAP_BASE_OFF	0x0020
#define	GT_PCICONF_IOMAP_BASE_OFF	0x0024
#define	GT_PCICONF_INTPIN_BASE_OFF	0x003C

#define GT_I2O_BASE					(0x1C00  + GALILEO_BASE_ADDR)
#define GT_I2O_INMSG_0_OFF			0x0010
#define GT_I2O_INMSG_1_OFF			0x0014
#define GT_I2O_OUTMSG_0_OFF			0x0018
#define GT_I2O_OUTMSG_1_OFF			0x001C
#define GT_I2O_IN_DOORBELL_OFF		0x0020
#define GT_I2O_OUT_DOORBELL_OFF		0x002C
#define GT_I2O_QBAR_OFF				0x0054
#define GT_I2O_INFREE_HEAD_OFF		0x0060
#define GT_I2O_INFREE_TAIL_OFF		0x0064
#define GT_I2O_INPOST_HEAD_OFF		0x0068
#define GT_I2O_INPOST_TAIL_OFF		0x006C
#define GT_I2O_OUTFREE_HEAD_OFF		0x0070
#define GT_I2O_OUTFREE_TAIL_OFF		0x0074
#define GT_I2O_OUTPOST_HEAD_OFF		0x0078
#define GT_I2O_OUTPOST_TAIL_OFF		0x007C
#define GT_I2O_INTOUT_MASK_OFF		0x0034
#define GT_I2O_INTIN_CAUSE_OFF		0x0024
#define GT_I2O_INTIN_MASK_OFF		0x0028
#define GT_I2O_QCTRL_OFF			0x0050
#define GT_I2O_INQ_VR_OFF			0x0040
#define GT_I2O_OUTQ_VR_OFF			0x0044

#define GT_I2O_INMSG_0_REG			(GT_I2O_BASE + GT_I2O_INMSG_0_OFF)
#define GT_I2O_INMSG_1_REG			(GT_I2O_BASE + GT_I2O_INMSG_1_OFF)
#define GT_I2O_OUTMSG_0_REG			(GT_I2O_BASE + GT_I2O_OUTMSG_0_OFF)
#define GT_I2O_OUTMSG_1_REG			(GT_I2O_BASE + GT_I2O_OUTMSG_1_OFF)
#define GT_I2O_IN_DOORBELL_REG		(GT_I2O_BASE + GT_I2O_IN_DOORBELL_OFF)
#define GT_I2O_OUT_DOORBELL_REG		(GT_I2O_BASE + GT_I2O_OUT_DOORBELL_OFF)
#define GT_I2O_QBAR_REG				(GT_I2O_BASE + GT_I2O_QBAR_OFF)
#define GT_I2O_INFREE_HEAD_REG		(GT_I2O_BASE + GT_I2O_INFREE_HEAD_OFF)
#define GT_I2O_INFREE_TAIL_REG		(GT_I2O_BASE + GT_I2O_INFREE_TAIL_OFF)
#define GT_I2O_INPOST_HEAD_REG		(GT_I2O_BASE + GT_I2O_INPOST_HEAD_OFF)
#define GT_I2O_INPOST_TAIL_REG		(GT_I2O_BASE + GT_I2O_INPOST_TAIL_OFF)
#define GT_I2O_OUTFREE_HEAD_REG		(GT_I2O_BASE + GT_I2O_OUTFREE_HEAD_OFF)
#define GT_I2O_OUTFREE_TAIL_REG		(GT_I2O_BASE + GT_I2O_OUTFREE_TAIL_OFF)
#define GT_I2O_OUTPOST_HEAD_REG		(GT_I2O_BASE + GT_I2O_OUTPOST_HEAD_OFF)
#define GT_I2O_OUTPOST_TAIL_REG		(GT_I2O_BASE + GT_I2O_OUTPOST_TAIL_OFF)
#define GT_I2O_INTOUT_MASK_REG		(GT_I2O_BASE + GT_I2O_INTOUT_MASK_OFF)
#define GT_I2O_INTIN_CAUSE_REG		(GT_I2O_BASE + GT_I2O_INTIN_CAUSE_OFF)
#define GT_I2O_INTIN_MASK_REG		(GT_I2O_BASE + GT_I2O_INTIN_MASK_OFF)
#define GT_I2O_QCTRL_REG			(GT_I2O_BASE + GT_I2O_QCTRL_OFF)
#define GT_I2O_INQ_VR_REG			(GT_I2O_BASE + GT_I2O_INQ_VR_OFF)
#define GT_I2O_OUTQ_VR_REG			(GT_I2O_BASE + GT_I2O_OUTQ_VR_OFF)
/*
**
**	Galileo Register Addresses
**
*/
#ifdef CLANGUAGE
#define	GT_CPU_CONFIG_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_CPU_CONFIG_OFF))
#define	GT_MULTI_GT_SUPPORT_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_MULTI_GT_SUPPORT_OFF))

#define	GT_PROC_RAS10_LO_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_PROC_RAS10_LO_OFF))
#define	GT_PROC_RAS10_HI_REG 		((unsigned long *)(GALILEO_BASE_ADDR+GT_PROC_RAS10_HI_OFF))
#define	GT_PROC_RAS32_LO_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_PROC_RAS32_LO_OFF))
#define	GT_PROC_RAS32_HI_REG 		((unsigned long *)(GALILEO_BASE_ADDR+GT_PROC_RAS32_HI_OFF))
#define	GT_PROC_CS20_LO_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_PROC_CS20_LO_OFF))
#define	GT_PROC_CS20_HI_REG 		((unsigned long *)(GALILEO_BASE_ADDR+GT_PROC_CS20_HI_OFF))
#define	GT_PROC_CS3BOOTCS_LO_REG	((unsigned long *)(GALILEO_BASE_ADDR+GT_PROC_CS3BOOTCS_LO_OFF))
#define	GT_PROC_CS3BOOTCS_HI_REG 	((unsigned long *)(GALILEO_BASE_ADDR+GT_PROC_CS3BOOTCS_HI_OFF))
#define	GT_PROC_PCI_IO_LO_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_PROC_PCI_IO_LO_OFF))
#define	GT_PROC_PCI_IO_HI_REG 		((unsigned long *)(GALILEO_BASE_ADDR+GT_PROC_PCI_IO_HI_OFF))
#define	GT_PROC_PCI_MEM_LO_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_PROC_PCI_MEM_LO_OFF))
#define	GT_PROC_PCI_MEM_HI_REG 		((unsigned long *)(GALILEO_BASE_ADDR+GT_PROC_PCI_MEM_HI_OFF))
#define	GT_PROC_INT_SPACE_REG 		((unsigned long *)(GALILEO_BASE_ADDR+GT_PROC_INT_SPACE_OFF))
#define	GT_PROC_BUSERR_LO_REG 		((unsigned long *)(GALILEO_BASE_ADDR+GT_PROC_BUSERR_LO_OFF))
#define	GT_PROC_BUSERR_HI_REG 		((unsigned long *)(GALILEO_BASE_ADDR+GT_PROC_BUSERR_HI_OFF))
#define	GT_PROC_PCI0_MEM1_LO_REG	((unsigned long *)(GALILEO_BASE_ADDR+GT_PROC_PCI0_MEM1_LO_OFF))
#define	GT_PROC_PCI0_MEM1_HI_REG	((unsigned long *)(GALILEO_BASE_ADDR+GT_PROC_PCI0_MEM1_HI_OFF))
#define	GT_PROC_PCI_1_MEM_LO_REG	((unsigned long *)(GALILEO_BASE_ADDR+GT_PROC_PCI_1_MEM_LO_OFF))
#define	GT_PROC_PCI_1_MEM_HI_REG	((unsigned long *)(GALILEO_BASE_ADDR+GT_PROC_PCI_1_MEM_HI_OFF))

#define	GT_DRAM_RAS0_LO_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_RAS0_LO_OFF))
#define	GT_DRAM_RAS0_HI_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_RAS0_HI_OFF))
#define	GT_DRAM_RAS1_LO_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_RAS1_LO_OFF))
#define	GT_DRAM_RAS1_HI_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_RAS1_HI_OFF))
#define	GT_DRAM_RAS2_LO_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_RAS2_LO_OFF))
#define	GT_DRAM_RAS2_HI_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_RAS2_HI_OFF))
#define	GT_DRAM_RAS3_LO_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_RAS3_LO_OFF))
#define	GT_DRAM_RAS3_HI_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_RAS3_HI_OFF))

#define	GT_DRAM_CS0_LO_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_CS0_LO_OFF)) 
#define	GT_DRAM_CS0_HI_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_CS0_HI_OFF))
#define	GT_DRAM_CS1_LO_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_CS1_LO_OFF))
#define	GT_DRAM_CS1_HI_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_CS1_HI_OFF)) 
#define	GT_DRAM_CS2_LO_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_CS2_LO_OFF)) 
#define	GT_DRAM_CS2_HI_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_CS2_HI_OFF)) 
#define	GT_DRAM_CS3_LO_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_CS3_LO_OFF)) 
#define	GT_DRAM_CS3_HI_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_CS3_HI_OFF)) 

#define	GT_DRAM_BOOTCS_LO_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_BOOTCS_LO_OFF))
#define	GT_DRAM_BOOTCS_HI_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_BOOTCS_HI_OFF))

#define	GT_DRAM_ADDRERR_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_ADDRERR_OFF))

#define	GT_DRAM_CONFIG_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_CONFIG_OFF))
#define	GT_DRAM_ADDR_DECODE_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_ADDR_DECODE_OFF))

#define	GT_DRAM0_PARMS_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM0_PARMS_OFF))
#define	GT_DRAM1_PARMS_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM1_PARMS_OFF))
#define	GT_DRAM2_PARMS_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM2_PARMS_OFF))
#define	GT_DRAM3_PARMS_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM3_PARMS_OFF))

#define	GT_DEV0_PARMS_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DEV0_PARMS_OFF))	
#define	GT_DEV1_PARMS_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DEV1_PARMS_OFF))
#define	GT_DEV2_PARMS_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DEV2_PARMS_OFF))	
#define	GT_DEV3_PARMS_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DEV3_PARMS_OFF))	
#define	GT_DRAM_OP_MODE_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DRAM_OP_MODE_OFF))
#define	GT_ADDR_DECODE_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_ADDR_DECODE_OFF))

#define	GT_DEV_BOOT_PARMS_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_DEV_BOOT_PARMS_OFF))

#define	GT_DMA_CH0_COUNT_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH0_COUNT_OFF))
#define	GT_DMA_CH1_COUNT_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH1_COUNT_OFF))
#define	GT_DMA_CH2_COUNT_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH2_COUNT_OFF))
#define	GT_DMA_CH3_COUNT_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH3_COUNT_OFF))

#define	GT_DMA_CH0_SRC_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH0_SRC_OFF))
#define	GT_DMA_CH1_SRC_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH1_SRC_OFF))
#define	GT_DMA_CH2_SRC_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH2_SRC_OFF))
#define	GT_DMA_CH3_SRC_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH3_SRC_OFF))

#define	GT_DMA_CH0_DEST_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH0_DEST_OFF))
#define	GT_DMA_CH1_DEST_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH1_DEST_OFF))
#define	GT_DMA_CH2_DEST_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH2_DEST_OFF))
#define	GT_DMA_CH3_DEST_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH3_DEST_OFF))

#define	GT_DMA_CH0_NEXT_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH0_NEXT_OFF))
#define	GT_DMA_CH1_NEXT_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH1_NEXT_OFF))
#define	GT_DMA_CH2_NEXT_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH2_NEXT_OFF))
#define	GT_DMA_CH3_NEXT_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH3_NEXT_OFF))

#define	GT_DMA_CH0_CONTROL_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH0_CONTROL_OFF))
#define	GT_DMA_CH1_CONTROL_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH1_CONTROL_OFF))
#define	GT_DMA_CH2_CONTROL_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH2_CONTROL_OFF))
#define	GT_DMA_CH3_CONTROL_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_CH3_CONTROL_OFF))

#define	GT_DMA_ARBITER_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_DMA_ARBITER_OFF))

#define	GT_TIMER0_REG				((unsigned long *)(GALILEO_BASE_ADDR+GT_TIMER0_OFF))
#define	GT_TIMER1_REG				((unsigned long *)(GALILEO_BASE_ADDR+GT_TIMER1_OFF))
#define	GT_TIMER2_REG				((unsigned long *)(GALILEO_BASE_ADDR+GT_TIMER2_OFF))
#define	GT_TIMER3_REG				((unsigned long *)(GALILEO_BASE_ADDR+GT_TIMER3_OFF))
#define	GT_TIMER_CONTROL_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_TIMER_CONTROL_OFF))

#define	GT_PCI_COMMAND_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_PCI_COMMAND_OFF))
#define	GT_PCI_RETRY_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_PCI_RETRY_OFF))
#define	GT_PCI_RAS10_BSIZE_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_PCI_RAS10_BSIZE_OFF))
#define	GT_PCI_RAS10_MAP_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_PCI_RAS10_MAP_OFF))
#define	GT_PCI_RAS32_MAP_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_PCI_RAS32_MAP_OFF))
#define	GT_PCI_RAS32_BSIZE_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_PCI_RAS32_BSIZE_OFF))
#define	GT_PCI_CS20_BSIZE_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_PCI_CS20_BSIZE_OFF))
#define	GT_PCI_BOOTCS_BSIZE_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_PCI_BOOTCS_BSIZE_OFF))
#define	GT_PCI_SERR_MASK_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_PCI_SERR_MASK_OFF))
#define	GT_PCI_INT_ACK_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_PCI_INT_ACK_OFF))
#define	GT_PCI_CONFIG_ADDR_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_PCI_CONFIG_ADDR_OFF)) 
#define	GT_PCI_CONFIG_DATA_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_PCI_CONFIG_DATA_OFF))

#define	GT_INT_CAUSE_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_INT_CAUSE_OFF))
#define	GT_INT_CPU_MASK_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_INT_CPU_MASK_OFF))
#define	GT_INT_PCI_MASK_REG			((unsigned long *)(GALILEO_BASE_ADDR+GT_INT_PCI_MASK_OFF))

#define	GT_PCICONF_DEVID_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_PCICONF_DEVID_OFF))
#define	GT_PCICONF_STATCMD_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_PCICONF_STATCMD_OFF))
#define	GT_PCICONF_REVID_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_PCICONF_REVID_OFF))
#define	GT_PCICONF_HEADER_REG		((unsigned long *)(GALILEO_BASE_ADDR+GT_PCICONF_HEADER_OFF))
#define	GT_PCICONF_RAS10_BASE_REG	((unsigned long *)(GALILEO_BASE_ADDR+GT_PCICONF_RAS10_BASE_OFF))
#define	GT_PCICONF_RAS32_BASE_REG	((unsigned long *)(GALILEO_BASE_ADDR+GT_PCICONF_RAS32_BASE_OFF))
#define	GT_PCICONF_CS20_BASE_REG	((unsigned long *)(GALILEO_BASE_ADDR+GT_PCICONF_CS20_BASE_OFF))
#define	GT_PCICONF_BOOTCS_BASE_REG	((unsigned long *)(GALILEO_BASE_ADDR+GT_PCICONF_BOOTCS_BASE_OFF))
#define	GT_PCICONF_MEMMAP_BASE_REG	((unsigned long *)(GALILEO_BASE_ADDR+GT_PCICONF_MEMMAP_BASE_OFF))
#define	GT_PCICONF_IOMAP_BASE_REG	((unsigned long *)(GALILEO_BASE_ADDR+GT_PCICONF_IOMAP_BASE_OFF))
#define	GT_PCICONF_INTPIN_BASE_REG	((unsigned long *)(GALILEO_BASE_ADDR+GT_PCICONF_INTPIN_BASE_OFF))
#else
#define	GT_CPU_CONFIG_REG			GALILEO_BASE_ADDR+GT_CPU_CONFIG_OFF
#define	GT_MULTI_GT_SUPPORT_REG		GALILEO_BASE_ADDR+GT_MULTI_GT_SUPPORT_OFF

#define	GT_PROC_RAS10_LO_REG		GALILEO_BASE_ADDR+GT_PROC_RAS10_LO_OFF
#define	GT_PROC_RAS10_HI_REG 		GALILEO_BASE_ADDR+GT_PROC_RAS10_HI_OFF
#define	GT_PROC_RAS32_LO_REG		GALILEO_BASE_ADDR+GT_PROC_RAS32_LO_OFF
#define	GT_PROC_RAS32_HI_REG 		GALILEO_BASE_ADDR+GT_PROC_RAS32_HI_OFF
#define	GT_PROC_CS20_LO_REG			GALILEO_BASE_ADDR+GT_PROC_CS20_LO_OFF
#define	GT_PROC_CS20_HI_REG 		GALILEO_BASE_ADDR+GT_PROC_CS20_HI_OFF
#define	GT_PROC_CS3BOOTCS_LO_REG	GALILEO_BASE_ADDR+GT_PROC_CS3BOOTCS_LO_OFF
#define	GT_PROC_CS3BOOTCS_HI_REG 	GALILEO_BASE_ADDR+GT_PROC_CS3BOOTCS_HI_OFF
#define	GT_PROC_PCI_IO_LO_REG		GALILEO_BASE_ADDR+GT_PROC_PCI_IO_LO_OFF
#define	GT_PROC_PCI_IO_HI_REG 		GALILEO_BASE_ADDR+GT_PROC_PCI_IO_HI_OFF
#define	GT_PROC_PCI_MEM_LO_REG		GALILEO_BASE_ADDR+GT_PROC_PCI_MEM_LO_OFF
#define	GT_PROC_PCI_MEM_HI_REG 		GALILEO_BASE_ADDR+GT_PROC_PCI_MEM_HI_OFF
#define	GT_PROC_INT_SPACE_REG 		GALILEO_BASE_ADDR+GT_PROC_INT_SPACE_OFF
#define	GT_PROC_BUSERR_LO_REG 		GALILEO_BASE_ADDR+GT_PROC_BUSERR_LO_OFF
#define	GT_PROC_BUSERR_HI_REG 		GALILEO_BASE_ADDR+GT_PROC_BUSERR_HI_OFF
#define	GT_PROC_PCI0_MEM1_LO_REG	GALILEO_BASE_ADDR+GT_PROC_PCI0_MEM1_LO_OFF
#define	GT_PROC_PCI0_MEM1_HI_REG	GALILEO_BASE_ADDR+GT_PROC_PCI0_MEM1_HI_OFF
#define	GT_PROC_PCI_1_MEM_LO_REG	GALILEO_BASE_ADDR+GT_PROC_PCI_1_MEM_LO_OFF
#define	GT_PROC_PCI_1_MEM_HI_REG	GALILEO_BASE_ADDR+GT_PROC_PCI_1_MEM_HI_OFF

#define	GT_DRAM_RAS0_LO_REG			GALILEO_BASE_ADDR+GT_DRAM_RAS0_LO_OFF
#define	GT_DRAM_RAS0_HI_REG			GALILEO_BASE_ADDR+GT_DRAM_RAS0_HI_OFF
#define	GT_DRAM_RAS1_LO_REG			GALILEO_BASE_ADDR+GT_DRAM_RAS1_LO_OFF
#define	GT_DRAM_RAS1_HI_REG			GALILEO_BASE_ADDR+GT_DRAM_RAS1_HI_OFF
#define	GT_DRAM_RAS2_LO_REG			GALILEO_BASE_ADDR+GT_DRAM_RAS2_LO_OFF
#define	GT_DRAM_RAS2_HI_REG			GALILEO_BASE_ADDR+GT_DRAM_RAS2_HI_OFF
#define	GT_DRAM_RAS3_LO_REG			GALILEO_BASE_ADDR+GT_DRAM_RAS3_LO_OFF
#define	GT_DRAM_RAS3_HI_REG			GALILEO_BASE_ADDR+GT_DRAM_RAS3_HI_OFF

#define	GT_DRAM_CS0_LO_REG			GALILEO_BASE_ADDR+GT_DRAM_CS0_LO_OFF 
#define	GT_DRAM_CS0_HI_REG			GALILEO_BASE_ADDR+GT_DRAM_CS0_HI_OFF 
#define	GT_DRAM_CS1_LO_REG			GALILEO_BASE_ADDR+GT_DRAM_CS1_LO_OFF 
#define	GT_DRAM_CS1_HI_REG			GALILEO_BASE_ADDR+GT_DRAM_CS1_HI_OFF 
#define	GT_DRAM_CS2_LO_REG			GALILEO_BASE_ADDR+GT_DRAM_CS2_LO_OFF 
#define	GT_DRAM_CS2_HI_REG			GALILEO_BASE_ADDR+GT_DRAM_CS2_HI_OFF 
#define	GT_DRAM_CS3_LO_REG			GALILEO_BASE_ADDR+GT_DRAM_CS3_LO_OFF 
#define	GT_DRAM_CS3_HI_REG			GALILEO_BASE_ADDR+GT_DRAM_CS3_HI_OFF 

#define	GT_DRAM_BOOTCS_LO_REG		GALILEO_BASE_ADDR+GT_DRAM_BOOTCS_LO_OFF
#define	GT_DRAM_BOOTCS_HI_REG		GALILEO_BASE_ADDR+GT_DRAM_BOOTCS_HI_OFF

#define	GT_DRAM_ADDRERR_REG			GALILEO_BASE_ADDR+GT_DRAM_ADDRERR_OFF

#define	GT_DRAM_CONFIG_REG			GALILEO_BASE_ADDR+GT_DRAM_CONFIG_OFF
#define	GT_DRAM_ADDR_DECODE_REG		GALILEO_BASE_ADDR+GT_DRAM_ADDR_DECODE_OFF

#define	GT_DRAM0_PARMS_REG			GALILEO_BASE_ADDR+GT_DRAM0_PARMS_OFF
#define	GT_DRAM1_PARMS_REG			GALILEO_BASE_ADDR+GT_DRAM1_PARMS_OFF
#define	GT_DRAM2_PARMS_REG			GALILEO_BASE_ADDR+GT_DRAM2_PARMS_OFF
#define	GT_DRAM3_PARMS_REG			GALILEO_BASE_ADDR+GT_DRAM3_PARMS_OFF

#define	GT_DEV0_PARMS_REG			GALILEO_BASE_ADDR+GT_DEV0_PARMS_OFF	
#define	GT_DEV1_PARMS_REG			GALILEO_BASE_ADDR+GT_DEV1_PARMS_OFF	
#define	GT_DEV2_PARMS_REG			GALILEO_BASE_ADDR+GT_DEV2_PARMS_OFF	
#define	GT_DEV3_PARMS_REG			GALILEO_BASE_ADDR+GT_DEV3_PARMS_OFF	
#define	GT_DRAM_OP_MODE_REG			GALILEO_BASE_ADDR+GT_DRAM_OP_MODE_OFF	
#define	GT_ADDR_DECODE_REG			GALILEO_BASE_ADDR+GT_ADDR_DECODE_OFF	

#define	GT_DEV_BOOT_PARMS_REG		GALILEO_BASE_ADDR+GT_DEV_BOOT_PARMS_OFF

#define	GT_DMA_CH0_COUNT_REG		GALILEO_BASE_ADDR+GT_DMA_CH0_COUNT_OFF
#define	GT_DMA_CH1_COUNT_REG		GALILEO_BASE_ADDR+GT_DMA_CH1_COUNT_OFF
#define	GT_DMA_CH2_COUNT_REG		GALILEO_BASE_ADDR+GT_DMA_CH2_COUNT_OFF
#define	GT_DMA_CH3_COUNT_REG		GALILEO_BASE_ADDR+GT_DMA_CH3_COUNT_OFF

#define	GT_DMA_CH0_SRC_REG			GALILEO_BASE_ADDR+GT_DMA_CH0_SRC_OFF
#define	GT_DMA_CH1_SRC_REG			GALILEO_BASE_ADDR+GT_DMA_CH1_SRC_OFF
#define	GT_DMA_CH2_SRC_REG			GALILEO_BASE_ADDR+GT_DMA_CH2_SRC_OFF
#define	GT_DMA_CH3_SRC_REG			GALILEO_BASE_ADDR+GT_DMA_CH3_SRC_OFF

#define	GT_DMA_CH0_DEST_REG			GALILEO_BASE_ADDR+GT_DMA_CH0_DEST_OFF
#define	GT_DMA_CH1_DEST_REG			GALILEO_BASE_ADDR+GT_DMA_CH1_DEST_OFF
#define	GT_DMA_CH2_DEST_REG			GALILEO_BASE_ADDR+GT_DMA_CH2_DEST_OFF
#define	GT_DMA_CH3_DEST_REG			GALILEO_BASE_ADDR+GT_DMA_CH3_DEST_OFF

#define	GT_DMA_CH0_NEXT_REG			GALILEO_BASE_ADDR+GT_DMA_CH0_NEXT_OFF
#define	GT_DMA_CH1_NEXT_REG			GALILEO_BASE_ADDR+GT_DMA_CH1_NEXT_OFF
#define	GT_DMA_CH2_NEXT_REG			GALILEO_BASE_ADDR+GT_DMA_CH2_NEXT_OFF
#define	GT_DMA_CH3_NEXT_REG			GALILEO_BASE_ADDR+GT_DMA_CH3_NEXT_OFF

#define	GT_DMA_CH0_CONTROL_REG		GALILEO_BASE_ADDR+GT_DMA_CH0_CONTROL_OFF
#define	GT_DMA_CH1_CONTROL_REG		GALILEO_BASE_ADDR+GT_DMA_CH1_CONTROL_OFF
#define	GT_DMA_CH2_CONTROL_REG		GALILEO_BASE_ADDR+GT_DMA_CH2_CONTROL_OFF
#define	GT_DMA_CH3_CONTROL_REG		GALILEO_BASE_ADDR+GT_DMA_CH3_CONTROL_OFF

#define	GT_DMA_ARBITER_REG			GALILEO_BASE_ADDR+GT_DMA_ARBITER_OFF

#define	GT_TIMER0_REG				GALILEO_BASE_ADDR+GT_TIMER0_OFF
#define	GT_TIMER1_REG				GALILEO_BASE_ADDR+GT_TIMER1_OFF
#define	GT_TIMER2_REG				GALILEO_BASE_ADDR+GT_TIMER2_OFF
#define	GT_TIMER3_REG				GALILEO_BASE_ADDR+GT_TIMER3_OFF
#define	GT_TIMER_CONTROL_REG		GALILEO_BASE_ADDR+GT_TIMER_CONTROL_OFF

#define	GT_PCI_COMMAND_REG			GALILEO_BASE_ADDR+GT_PCI_COMMAND_OFF
#define	GT_PCI_RETRY_REG			GALILEO_BASE_ADDR+GT_PCI_RETRY_OFF
#define	GT_PCI_RAS10_MAP_REG		GALILEO_BASE_ADDR+GT_PCI_RAS10_MAP_OFF
#define	GT_PCI_RAS32_MAP_REG		GALILEO_BASE_ADDR+GT_PCI_RAS32_MAP_OFF
#define	GT_PCI_RAS10_BSIZE_REG		GALILEO_BASE_ADDR+GT_PCI_RAS10_BSIZE_OFF
#define	GT_PCI_RAS32_BSIZE_REG		GALILEO_BASE_ADDR+GT_PCI_RAS32_BSIZE_OFF
#define	GT_PCI_CS20_BSIZE_REG		GALILEO_BASE_ADDR+GT_PCI_CS20_BSIZE_OFF
#define	GT_PCI_BOOTCS_BSIZE_REG		GALILEO_BASE_ADDR+GT_PCI_BOOTCS_BSIZE_OFF
#define	GT_PCI_SERR_MASK_REG		GALILEO_BASE_ADDR+GT_PCI_SERR_MASK_OFF
#define	GT_PCI_INT_ACK_REG			GALILEO_BASE_ADDR+GT_PCI_INT_ACK_OFF
#define	GT_PCI_CONFIG_ADDR_REG		GALILEO_BASE_ADDR+GT_PCI_CONFIG_ADDR_OFF
#define	GT_PCI_CONFIG_DATA_REG		GALILEO_BASE_ADDR+GT_PCI_CONFIG_DATA_OFF

#define	GT_INT_CAUSE_REG			GALILEO_BASE_ADDR+GT_INT_CAUSE_OFF
#define	GT_INT_CPU_MASK_REG			GALILEO_BASE_ADDR+GT_INT_CPU_MASK_OFF
#define	GT_INT_PCI_MASK_REG			GALILEO_BASE_ADDR+GT_INT_PCI_MASK_OFF

#define	GT_PCICONF_DEVID_REG		GALILEO_BASE_ADDR+GT_PCICONF_DEVID_OFF
#define	GT_PCICONF_STATCMD_REG		GALILEO_BASE_ADDR+GT_PCICONF_STATCMD_OFF
#define	GT_PCICONF_REVID_REG		GALILEO_BASE_ADDR+GT_PCICONF_REVID_OFF
#define	GT_PCICONF_HEADER_REG		GALILEO_BASE_ADDR+GT_PCICONF_HEADER_OFF
#define	GT_PCICONF_RAS10_BASE_REG	GALILEO_BASE_ADDR+GT_PCICONF_RAS10_BASE_OFF
#define	GT_PCICONF_RAS32_BASE_REG	GALILEO_BASE_ADDR+GT_PCICONF_RAS32_BASE_OFF
#define	GT_PCICONF_CS20_BASE_REG	GALILEO_BASE_ADDR+GT_PCICONF_CS20_BASE_OFF
#define	GT_PCICONF_BOOTCS_BASE_REG	GALILEO_BASE_ADDR+GT_PCICONF_BOOTCS_BASE_OFF
#define	GT_PCICONF_MEMMAP_BASE_REG	GALILEO_BASE_ADDR+GT_PCICONF_MEMMAP_BASE_OFF
#define	GT_PCICONF_IOMAP_BASE_REG	GALILEO_BASE_ADDR+GT_PCICONF_IOMAP_BASE_OFF	
#define	GT_PCICONF_INTPIN_BASE_REG	GALILEO_BASE_ADDR+GT_PCICONF_INTPIN_BASE_OFF
#endif

/*
**
**	Galileo Register Definitions
**
*/

/* Control Register: GT_CPU_CONFIG_REG */
#define	GT_PCI_2GIG			0x00200000

/* DMA Arbiter Control Register: GT_DMA_ARBITER_REG */
#define	GT_DAREG_PRICH_10RR		0x00
#define	GT_DAREG_PRICH_1OVR0	0x01
#define	GT_DAREG_PRICH_0OVR1	0x02

#define	GT_DAREG_PRICH_32RR		0x00
#define	GT_DAREG_PRICH_3OVR2	0x04
#define	GT_DAREG_PRICH_2OVR3	0x08

#define	GT_DAREG_PRIGRP_RR		0x00
#define	GT_DAREG_PRIGRP_23OVR01	0x10
#define	GT_DAREG_PRIGRP_01OVR23	0x20

#define	GT_DAREG_PRIOPT_HIREL	0x00
#define	GT_DAREG_PRIOPT_HIDEV	0x40

/* Timer/Counter Control Register: GT_TIMER_CONTROL_REG */
#define	GT_TCREG_ENTC0		0x01
#define	GT_TCREG_SELTC0		0x02
#define	GT_TCREG_ENTC1		0x04
#define	GT_TCREG_SELTC1		0x08
#define	GT_TCREG_ENTC2		0x10
#define	GT_TCREG_SELTC2		0x20
#define	GT_TCREG_ENTC3		0x40
#define	GT_TCREG_SELTC3		0x80

/* Interrupt Cause Register: GT_INT_CAUSE_REG */
#define	GT_ICREG_INTSUM		0x00000001
#define	GT_ICREG_MEMOUT		0x00000002
#define	GT_ICREG_DMAOUT		0x00000004
#define	GT_ICREG_CPUOUT		0x00000008
#define	GT_ICREG_DMA0DONE	0x00000010
#define	GT_ICREG_DMA1DONE	0x00000020
#define	GT_ICREG_DMA2DONE	0x00000040
#define	GT_ICREG_DMA3DONE	0x00000080
#define	GT_ICREG_TMR0EXP	0x00000100
#define	GT_ICREG_TMR1EXP	0x00000200
#define	GT_ICREG_TMR2EXP	0x00000400
#define	GT_ICREG_TMR3EXP	0x00000800
#define	GT_ICREG_MASRDERR	0x00001000
#define	GT_ICREG_SLVWRERR	0x00002000
#define	GT_ICREG_MASWRERR	0x00004000
#define	GT_ICREG_SLVRDERR	0x00008000
#define	GT_ICREG_ADDRERR	0x00010000
#define	GT_ICREG_MEMERR		0x00020000
#define	GT_ICREG_MASABORT	0x00040000
#define	GT_ICREG_TARABORT	0x00080000
#define	GT_ICREG_RETRYCTR	0x00100000
#define	GT_ICREG_CPUINT		0x03E00000
#define	GT_ICREG_PCIINT		0x3C000000
#define	GT_ICREG_CPUINTSUM	0x40000000
#define	GT_ICREG_PCIINTSUM	0x80000000

/* Interrupt Mask Register: GT_INT_CPU_MASK_REG */
#define	GT_ICMREG_INTSUM	0x00000001
#define	GT_ICMREG_MEMOUT	0x00000002
#define	GT_ICMREG_DMAOUT	0x00000004
#define	GT_ICMREG_CPUOUT	0x00000008
#define	GT_ICMREG_DMA0DONE	0x00000010
#define	GT_ICMREG_DMA1DONE	0x00000020
#define	GT_ICMREG_DMA2DONE	0x00000040
#define	GT_ICMREG_DMA3DONE	0x00000080
#define	GT_ICMREG_TMR0EXP	0x00000100
#define	GT_ICMREG_TMR1EXP	0x00000200
#define	GT_ICMREG_TMR2EXP	0x00000400
#define	GT_ICMREG_TMR3EXP	0x00000800
#define	GT_ICMREG_MASRDERR	0x00001000
#define	GT_ICMREG_SLVWRERR	0x00002000
#define	GT_ICMREG_MASWRERR	0x00004000
#define	GT_ICMREG_SLVRDERR	0x00008000
#define	GT_ICMREG_ADDRERR	0x00010000
#define	GT_ICMREG_MEMERR	0x00020000
#define	GT_ICMREG_MASABORT	0x00040000
#define	GT_ICMREG_TARABORT	0x00080000
#define	GT_ICMREG_RETRYCTR	0x00100000
#define	GT_ICMREG_CPUINT	0x03E00000
#define	GT_ICMREG_PCIINT	0x3C000000
#define	GT_ICMREG_CPUINTSUM	0x40000000
#define	GT_ICMREG_PCIINTSUM	0x80000000

/* Interrupt Mask Register: GT_INT_PCI_MASK_REG */
#define	GT_IPMREG_INTSUM	0x00000001
#define	GT_IPMREG_MEMOUT	0x00000002
#define	GT_IPMREG_DMAOUT	0x00000004
#define	GT_IPMREG_CPUOUT	0x00000008
#define	GT_IPMREG_DMA0DONE	0x00000010
#define	GT_IPMREG_DMA1DONE	0x00000020
#define	GT_IPMREG_DMA2DONE	0x00000040
#define	GT_IPMREG_DMA3DONE	0x00000080
#define	GT_IPMREG_TMR0EXP	0x00000100
#define	GT_IPMREG_TMR1EXP	0x00000200
#define	GT_IPMREG_TMR2EXP	0x00000400
#define	GT_IPMREG_TMR3EXP	0x00000800
#define	GT_IPMREG_MASRDERR	0x00001000
#define	GT_IPMREG_SLVWRERR	0x00002000
#define	GT_IPMREG_MASWRERR	0x00004000
#define	GT_IPMREG_SLVRDERR	0x00008000
#define	GT_IPMREG_ADDRERR	0x00010000
#define	GT_IPMREG_MEMERR	0x00020000
#define	GT_IPMREG_MASABORT	0x00040000
#define	GT_IPMREG_TARABORT	0x00080000
#define	GT_IPMREG_RETRYCTR	0x00100000
#define	GT_IPMREG_CPUINT	0x03E00000
#define	GT_IPMREG_PCIINT	0x3C000000
#define	GT_IPMREG_CPUINTSUM	0x40000000
#define	GT_IPMREG_PCIINTSUM	0x80000000

/* DMA Control Register Masks */
#define		GT_DMA_FLYBYEN		0x00000001
#define		GT_DMA_RDWRFLY		0x00000002
#define		GT_DMA_NOCHAIN_MODE	0x00000200
#define		GT_DMA_INT_MODE		0x00000400
#define		GT_DMA_BLOCK_MODE	0x00000800
#define		GT_DMA_CHAN_EN		0x00001000
#define		GT_DMA_FET_NEXTREC	0x00002000
#define		GT_DMA_ACT_STS		0x00004000
#define		GT_DMA_SDA			0x00008000
#define		GT_DMA_MDREQ		0x00010000
#define		GT_DMA_CDE			0x00020000
#define		GT_DMA_EOTE			0x00040000
#define		GT_DMA_EOTIE		0x00080000
#define		GT_DMA_ABR			0x00100000
#define		GT_DMA_DMAREG_TIMER	0x10000000

#define		GT_DMA_SDIR_MASK	0x0000000C
#define		GT_DMA_SDIR_INC		0x00000000
#define		GT_DMA_SDIR_DEC		0x00000004
#define		GT_DMA_SDIR_HOLD	0x00000008

#define		GT_DMA_DDIR_MASK	0x00000030
#define		GT_DMA_DDIR_INC		0x00000000
#define		GT_DMA_DDIR_DEC		0x00000010
#define		GT_DMA_DDIR_HOLD	0x00000020

#define		GT_DMA_XMIT_MASK	0x000001C0
#define		GT_DMA_XMIT_1		0x00000140
#define		GT_DMA_XMIT_2		0x00000180
#define		GT_DMA_XMIT_4		0x00000080
#define		GT_DMA_XMIT_8		0x00000000
#define		GT_DMA_XMIT_16		0x00000040
#define		GT_DMA_XMIT_32		0x000000C0
#define		GT_DMA_XMIT_64		0x000001C0

#define		GT_DMA_SLP_MASK		0x00600000
#define		GT_DMA_SLP_NO		0x00000000
#define		GT_DMA_SLP_PCI0		0x00200000
#define		GT_DMA_SLP_PCI1		0x00400000

#define		GT_DMA_DLP_MASK		0x01800000
#define		GT_DMA_DLP_NO		0x00000000
#define		GT_DMA_DLP_PCI0		0x00800000
#define		GT_DMA_DLP_PCI1		0x01000000

#define		GT_DMA_RLP_MASK		0x06000000
#define		GT_DMA_RLP_NO		0x00000000
#define		GT_DMA_RLP_PCI0		0x02000000
#define		GT_DMA_RLP_PCI1		0x04000000


/*
**
** Default Register Values for the Galileo
**
*/
#ifdef INCLUDE_EV64120
#define GT_CPU_IF_CONFIG_DEFAULT	(0x0000)
#define GT_RAS10_LOW_DEFAULT		(0x0000)
#define GT_RAS10_HIGH_DEFAULT		(0x0007)
#define GT_RAS32_LOW_DEFAULT		(0x0008)
#define GT_RAS32_HIGH_DEFAULT		(0x000f)
#define GT_CS20_LOW_DEFAULT		(0x00E0)
#define GT_CS20_HIGH_DEFAULT		(0x0070)
#define GT_CS3BOOTCS_LOW_DEFAULT	(0x00F8)
#define GT_CS3BOOTCS_HIGH_DEFAULT	(0x007F)
#define GT_PCI_IO_LOW_DEFAULT		(0x0080)
#define GT_PCI_IO_HIGH_DEFAULT		(0x000f)
#define GT_PCI_MEM_LOW_DEFAULT		(0x0090)
#define GT_PCI_MEM_HIGH_DEFAULT		(0x001F)
#define GT_PCI0_MEM1_LOW_DEFAULT	(0x0790)
#define GT_PCI0_MEM1_HIGH_DEFAULT	(0x001f)
#define GT_INTERNAL_SPACE_DEFAULT	(0x00A0)
#define GT_DRAM_RAS0_LOW_DEFAULT	(0x0000)
#define GT_DRAM_RAS0_HIGH_DEFAULT	(0x0007)
#define GT_DRAM_RAS1_LOW_DEFAULT	(0x0008)
#define GT_DRAM_RAS1_HIGH_DEFAULT	(0x000f)
#define GT_DRAM_RAS2_LOW_DEFAULT	(0x0010)
#define GT_DRAM_RAS2_HIGH_DEFAULT	(0x0017)
#define GT_DRAM_RAS3_LOW_DEFAULT	(0x0018)
#define GT_DRAM_RAS3_HIGH_DEFAULT	(0x001f)
#define GT_DRAM_CS0_LOW_DEFAULT		(0x00C0)
#define GT_DRAM_CS0_HIGH_DEFAULT	(0x00C7)
#define GT_DRAM_CS1_LOW_DEFAULT		(0x00C8)
#define GT_DRAM_CS1_HIGH_DEFAULT	(0x00Cf)
#define GT_DRAM_CS2_LOW_DEFAULT		(0x00d0)
#define GT_DRAM_CS2_HIGH_DEFAULT	(0x00df)
#define GT_DRAM_CS3_LOW_DEFAULT		(0x00f0)
#define GT_DRAM_CS3_HIGH_DEFAULT	(0x00fb)
#define GT_DRAM_BOOTCS_LOW_DEFAULT	(0x00FC)
#define GT_DRAM_BOOTCS_HIGH_DEFAULT	(0x00Ff)

#define GT_PCI_VENDOR_ID      		(0x000011AB)
#define GT_PCI_CONFIG_CYCLE		(0x80000000)
#define GT_PCI_STATCMD_DEFAULT		(0x00000007)
#define GT_PCI_RETRY_DEFAULT		(0x0000FFFF)
#define GT_PCI_HEADER_DEFAULT		(0x00000F07)
#define GT_DRAM_CONFIG_DEFAULT		(0x00008200)
#define GT_DRAM_ADDR_DECODE_DEFAULT	(0x0000000a)
#define	GT_PCI_RAS10_BSIZE_DEFAULT	(0x00FFF000)
#define	GT_PCI_RAS32_BSIZE_DEFAULT	(0x00FFF000)

#define GT_DRAM0_PARMS_DEFAULT		(0x0000854D)
#define GT_DRAM1_PARMS_DEFAULT		(0x0000854D)
#define GT_DRAM2_PARMS_DEFAULT		(0x0000854D)
#define GT_DRAM3_PARMS_DEFAULT		(0x0000854D)
#define GT_DEV0_PARMS_DEFAULT		(0x386FFFFF)
#define GT_DEV1_PARMS_DEFAULT		(0x386FFFFF)
#define GT_DEV2_PARMS_DEFAULT		(0x144FFFFF)
#define GT_DEV3_PARMS_DEFAULT		(0x167FFFFF)
#define GT_DEV_BOOT_PARMS_DEFAULT	(0x0005DC44)
#define GT_DRAM_OP_MODE_DEFAULT		(0x00000000)
#define GT_ADDR_DECODE_DEFAULT		(0x00000002)

#else /* INCLUDE_EV64120 */

#define GT_CPU_IF_CONFIG_DEFAULT	(0x00080000)
#define GT_MULTI_GT_SUPPORT_DEFAULT	(0x0003)
#define GT_RAS10_LOW_DEFAULT		(0x0000)
#define GT_RAS10_HIGH_DEFAULT		(0x007F)
#define GT_RAS32_LOW_DEFAULT		(0x0080)
#define GT_RAS32_HIGH_DEFAULT		(0x007F)
#define GT_CS20_LOW_DEFAULT		(0x03E0)
#define GT_CS20_HIGH_DEFAULT		(0x006F)
#define GT_CS3BOOTCS_LOW_DEFAULT	(0x03F8)
#define GT_CS3BOOTCS_HIGH_DEFAULT	(0x007F)
#define GT_PCI_IO_LOW_DEFAULT		(0x0380)
#define GT_PCI_IO_HIGH_DEFAULT		(0x000f)
#define GT_PCI_MEM_LOW_DEFAULT		(0x0390)
#define GT_PCI_MEM_HIGH_DEFAULT		(0x001F)
#define GT_PCI0_MEM1_LOW_DEFAULT	(0x0790)
#define GT_PCI0_MEM1_HIGH_DEFAULT	(0x001f)
#define GT_INTERNAL_SPACE_DEFAULT	(0x03A0)
#define GT_DRAM_RAS0_LOW_DEFAULT	(0x0000)
#define GT_DRAM_RAS0_HIGH_DEFAULT	(0x007F)
#define GT_DRAM_RAS1_LOW_DEFAULT	(0x0080)
#define GT_DRAM_RAS1_HIGH_DEFAULT	(0x00FF)
#define GT_DRAM_RAS2_LOW_DEFAULT	(0x0000)
#define GT_DRAM_RAS2_HIGH_DEFAULT	(0x007F)
#define GT_DRAM_RAS3_LOW_DEFAULT	(0x0080)
#define GT_DRAM_RAS3_HIGH_DEFAULT	(0x00FF)
#define GT_DRAM_CS0_LOW_DEFAULT		(0x00C0)
#define GT_DRAM_CS0_HIGH_DEFAULT	(0x00C7)
#define GT_DRAM_CS1_LOW_DEFAULT		(0x00C8)
#define GT_DRAM_CS1_HIGH_DEFAULT	(0x00Cf)
#define GT_DRAM_CS2_LOW_DEFAULT		(0x00d0)
#define GT_DRAM_CS2_HIGH_DEFAULT	(0x00df)
#define GT_DRAM_CS3_LOW_DEFAULT		(0x00f0)
#define GT_DRAM_CS3_HIGH_DEFAULT	(0x00fb)
#define GT_DRAM_BOOTCS_LOW_DEFAULT	(0x00FC)
#define GT_DRAM_BOOTCS_HIGH_DEFAULT	(0x00Ff)

#define GT_PCI_VENDOR_ID      		(0x000011AB)
#define GT_PCI_CONFIG_CYCLE		(0x80000000)
#define GT_PCI_STATCMD_DEFAULT		(0x00000007)
#define GT_PCI_RETRY_DEFAULT		(0x0000FFFF)
#define GT_PCI_HEADER_DEFAULT		(0x00000F07)
	
#define GT_DRAM_CONFIG_DEFAULT		(0x00108468)
#define GT_DRAM_ADDR_DECODE_DEFAULT	(0x00000002)
#define	GT_PCI_RAS10_BSIZE_DEFAULT	(0x00FFF000)
#define	GT_PCI_RAS32_BSIZE_DEFAULT	(0x00FFF000)

#define GT_DRAM0_PARMS_DEFAULT		(0x00108861)
#define GT_DRAM1_PARMS_DEFAULT		(0x00108861)
#define GT_DRAM2_PARMS_DEFAULT		(0x00108861)
#define GT_DRAM3_PARMS_DEFAULT		(0x00108861)
#define GT_DEV0_PARMS_DEFAULT		(0x3C47944B)	/* UART */
#define GT_DEV1_PARMS_DEFAULT		(0x0035D0E3)	/* Status Reg */
#define GT_DEV2_PARMS_DEFAULT		(0x00791443)	/* Flash Mem */
#define GT_DEV3_PARMS_DEFAULT		(0x006FD557)	/* LEDS */
#define GT_DEV_BOOT_PARMS_DEFAULT	(0x3C4FFBBB) 

#define GT_DRAM_OP_MODE_DEFAULT		(0x00000000)
	
#endif /* INCLUDE_EV64120 */



/* ENDIANESS NOTE: It seems that the GT-64120 needs to be programmed in little
** endian mode, regardless of the endianess of the system and the position of
** the jumper at J23 on the EV-64120.  The values returned by the GT-64120 for
** internal registers are also little endian, and need to be interpreted.
** However, the values returned by the GT-64120 for other pci activity are not
** little endian, and do not require byte swapping.
**
** The following macro will byte swap a doubleword as a (hopefully) temporary
** workaround to this misbehavior.
*/
#define GTREG(X) 	\
(((X)&0xff00)<<8)+(((X)&0xff0000)>>8)+(((X)&0xff000000)>>24)+(((X)&0xff)<<24)

#define GT_RESET_RAS10_LOW_DEFAULT	GTREG(0x000007FF)
#define GT_RESET_RAS10_HI_DEFAULT	GTREG(0x00000000)
#define GT_RESET_RAS32_LOW_DEFAULT	GTREG(0x000007FF)
#define GT_RESET_RAS32_HI_DEFAULT	GTREG(0x00000000)
#define GT_RESET_DRAM_RAS0_LOW_DEFAULT	GTREG(0x000007FF)
#define GT_RESET_DRAM_RAS0_HI_DEFAULT	GTREG(0x00000000)
#define GT_RESET_DRAM_RAS1_LOW_DEFAULT	GTREG(0x000007FF)
#define GT_RESET_DRAM_RAS1_HI_DEFAULT	GTREG(0x00000000)
#define GT_RESET_DRAM_RAS2_LOW_DEFAULT	GTREG(0x000007FF)
#define GT_RESET_DRAM_RAS2_HI_DEFAULT	GTREG(0x00000000)
#define GT_RESET_DRAM_RAS3_LOW_DEFAULT	GTREG(0x000007FF)
#define GT_RESET_DRAM_RAS3_HI_DEFAULT	GTREG(0x00000000)
#define GT_RESET_DRAM_CONFIG_DEFAULT	GTREG(0x000000a0)
	
#endif /* GALILEO_H */
