/*************************************************************************
 * This material is a confidential trade secret and proprietary 
 * information of ConvergeNet Technologies, Inc. which may not be 
 * reproduced, used, sold or transferred to any third party without the 
 * prior written consent of ConvergeNet Technologies, Inc.  This material 
 * is also copyrighted as an unpublished work under sections 104 and 408 
 * of Title 17 of the United States Code.  Law prohibits unauthorized 
 * use, copying or reproduction.
 *
 * File: hw.h
 * 
 * Description:
 * This file contains hardware register map for Odyssey System
 * 
 * Update Log:
 * 10/28/99 Jeff Nespor: Updated CPU_LEDS_PHYS_ADDR again for E2 boards.
 * 05/17/99 Jim Frandeen: Updated CPU_LEDS_PHYS_ADDR
 * 05/03/99 Sudhir Kasargod: Added UART Definitions for the ports E,F,G,H
 * 							 on HBC
 * 10/12/98 Raghava Kondapalli: Added extra UART Definitions
 * XX/XX/98 Jeff Nespor:	Created 
 ************************************************************************/

#ifndef HW_H
#define HW_H

#define KSEG0_BASE_ADDR			0x80000000
#define KSEG1_BASE_ADDR			0xA0000000

#define	K0BASE 		0x80000000
#define	K0SIZE 		0x20000000
#define	K1BASE 		0xa0000000
#define	K1SIZE 		0x20000000
#define K2BASE          0xc0000000


/*
**	An example:
**
#define CMD_REG_1_PHYS_ADDR		0x14000004
#define CMD_REG_1_KSEG1_ADDR	((unsigned long *)((CMD_REG_1_PHYS_ADDR)+(KSEG1_BASE_ADDR)))
#define	CMD_REG_1				(CMD_REG_1_KSEG1_ADDR)
**
*/

#define	MB(n)				((1024 *1024) * (n))

/*
 * Physical Address Space
 */
#define	PCI_IO_BASE_PHYS_ADDR		0x10000000
#define	PCI_MEMORY_BASE_PHYS_ADDR	0x12000000
#define	GALILEO_BASE_PHYS_ADDR		0x14000000
#define	RTC_REG_BASE_PHYS_ADDR		0x1C110000
#define	DRAM_CONFIG_REG_PHYS_ADDR	0x1C110032
#define	WATCHDOG_TIMER_PHYS_ADDR	0x1C110033
#define	CONFIG_REG0_PHYS_ADDR		0x1C110049
#define	CONFIG_REG1_PHYS_ADDR		0x1C11004A
#define	BOOT_FLASH_BASE_PHYS_ADDR	0x1FC00000
#define	BOOT_FLASH_END_PHYS_ADDR	0x1FC7FFFF
#define	FLASH_BASE_PHYS_ADDR		0x1FC80000
#define	FLASH_END_PHYS_ADDR		0x1FCFFFFF

#define MAX_MEMORY_BANK_SIZE 		MB(256)
#ifdef INCLUDE_ODYSSEY
#define	SYS_MEMORY_BANK_SIZE		MB(128)
#define UART_PORTA_PHY_ADDR		0x1C000000
#define UART_PORTB_PHY_ADDR		0x1C010000
#define UART_PORTC_PHY_ADDR		0x1C020000
#define UART_PORTD_PHY_ADDR		0x1C030000
#define UART_PORTE_PHY_ADDR		0x1C040000
#define UART_PORTF_PHY_ADDR		0x1C050000
#define UART_PORTG_PHY_ADDR		0x1C060000
#define UART_PORTH_PHY_ADDR		0x1C070000
#define	DRAM0_BASE_PHYS_ADDR		0x00000000
#define DRAM0_END_PHYS_ADDR		(MB(128) - 1)
#define	DRAM1_BASE_PHYS_ADDR		(MB(128))
#define DRAM1_END_PHYS_ADDR		(MB(256) - 1)
#define	DRAM2_BASE_PHYS_ADDR		(MB(1024))
#define DRAM2_END_PHYS_ADDR		(MB(1152) - 1)
#define	DRAM3_BASE_PHYS_ADDR		(MB(1152))
#define DRAM3_END_PHYS_ADDR		(MB(1280) - 1)
#define	DRAM10_BASE_PHYS_ADDR		0x00000000
#define	DRAM10_END_PHYS_ADDR		((2 * DRAM_SIZE) - 1)
#define	DRAM32_BASE_PHYS_ADDR		(MB(1024))
#define	DRAM32_END_PHYS_ADDR		(DRAM32_BASE_PHYS_ADDR +\
						((2 * DRAM_SIZE)) - 1)
#define CPU_LEDS_PHYS_ADDR		(0x1C080000)
#else
#define	SYS_MEMORY_BANK_SIZE		MB(16)
#define	DRAM_BASE_PHYS_ADDR		0x00000000
#define	DRAM0_BASE_PHYS_ADDR		0x00000000
#define	DRAM0_END_PHYS_ADDR		(MB(16) - 1)
#define	DRAM1_BASE_PHYS_ADDR		(MB(16))	/* Not Present */
#define	DRAM1_END_PHYS_ADDR		(MB(32) - 1)	/* Not Present */
#define	DRAM2_BASE_PHYS_ADDR		(MB(16))
#define DRAM2_END_PHYS_ADDR		(MB(32) - 1)	
#define	DRAM3_BASE_PHYS_ADDR		(MB(1152))	/* Not Present */
#define DRAM3_END_PHYS_ADDR		(MB(1280) - 1)	/* Not Present */
#define	DRAM10_BASE_PHYS_ADDR		0x00000000
#define	DRAM32_BASE_PHYS_ADDR		(MB(16))
#define	DUART_BASE_PHYS_ADDR		0x1D000000
#define	CPU_LEDS_PHYS_ADDR		0x1C110031

#endif /* INCLUDE_ODYSSEY */

/*
** kseg1 (uncached and unmapped) Address Space
*/
#define	DRAM0_BASE_KSEG1_ADDR		(DRAM0_BASE_PHYS_ADDR+KSEG1_BASE_ADDR)
#define	DRAM0_END_KSEG1_ADDR		(DRAM0_END_PHYS_ADDR+KSEG1_BASE_ADDR)
#define	DRAM1_BASE_KSEG1_ADDR		(DRAM1_BASE_PHYS_ADDR+KSEG1_BASE_ADDR)
#define	DRAM1_END_KSEG1_ADDR		(DRAM1_END_PHYS_ADDR+KSEG1_BASE_ADDR)
#define	PCI_IO_BASE_KSEG1_ADDR		(PCI_IO_BASE_PHYS_ADDR+KSEG1_BASE_ADDR)
#define	PCI_MEMORY_BASE_KSEG1_ADDR	(PCI_MEMORY_BASE_PHYS_ADDR+KSEG1_BASE_ADDR)
#define	GALILEO_BASE_KSEG1_ADDR		(GALILEO_BASE_PHYS_ADDR+KSEG1_BASE_ADDR)
#define	SHARED_MEM_BASE_KSEG1_ADDR	(SHARED_MEM_BASE_PHYS_ADDR+KSEG1_BASE_ADDR)
#define	RTC_REG_BASE_KSEG1_ADDR		(RTC_REG_BASE_PHYS_ADDR+KSEG1_BASE_ADDR)
#define	DUART_BASE_KSEG1_ADDR		(DUART_BASE_PHYS_ADDR+KSEG1_BASE_ADDR)
#define	CPU_LEDS_KSEG1_ADDR			(CPU_LEDS_PHYS_ADDR+KSEG1_BASE_ADDR)
#define	DRAM_CONFIG_REG_KSEG1_ADDR	(DRAM_CONFIG_REG_PHYS_ADDR+KSEG1_BASE_ADDR)
#define	WATCHDOG_TIMER_KSEG1_ADDR	(WATCHDOG_TIMER_PHYS_ADDR+KSEG1_BASE_ADDR)
#define	CAM_BASE_KSEG1_ADDR			(CAM_BASE_PHYS_ADDR+KSEG1_BASE_ADDR)
#define	CONFIG_REG0_KSEG1_ADDR		(CONFIG_REG0_PHYS_ADDR+KSEG1_BASE_ADDR)
#define	CONFIG_REG1_KSEG1_ADDR		(CONFIG_REG1_PHYS_ADDR+KSEG1_BASE_ADDR)
#define	BOOT_FLASH_BASE_KSEG1_ADDR	(BOOT_FLASH_BASE_PHYS_ADDR+KSEG1_BASE_ADDR)
#define	BOOT_FLASH_END_KSEG1_ADDR	(BOOT_FLASH_END_PHYS_ADDR+KSEG1_BASE_ADDR)
#define	FLASH_BASE_KSEG1_ADDR		(FLASH_BASE_PHYS_ADDR+KSEG1_BASE_ADDR)
#define	FLASH_END_KSEG1_ADDR		(FLASH_END_PHYS_ADDR+KSEG1_BASE_ADDR)

#ifdef INCLUDE_ODYSSEY
#define UART_PORTA_KSEG1_ADDR		(UART_PORTA_PHY_ADDR + KSEG1_BASE_ADDR)
#define UART_PORTB_KSEG1_ADDR		(UART_PORTB_PHY_ADDR + KSEG1_BASE_ADDR)
#define UART_PORTC_KSEG1_ADDR		(UART_PORTC_PHY_ADDR + KSEG1_BASE_ADDR)
#define UART_PORTD_KSEG1_ADDR		(UART_PORTD_PHY_ADDR + KSEG1_BASE_ADDR)
#define UART_PORTE_KSEG1_ADDR		(UART_PORTE_PHY_ADDR + KSEG1_BASE_ADDR)
#define UART_PORTF_KSEG1_ADDR		(UART_PORTF_PHY_ADDR + KSEG1_BASE_ADDR)
#define UART_PORTG_KSEG1_ADDR		(UART_PORTG_PHY_ADDR + KSEG1_BASE_ADDR)
#define UART_PORTH_KSEG1_ADDR		(UART_PORTH_PHY_ADDR + KSEG1_BASE_ADDR)
#endif /* INCLUDE_ODYSSEY */

/*
** kseg0 (cached and unmapped) Address Space
*/
#define	DRAM0_BASE_KSEG0_ADDR		(DRAM0_BASE_PHYS_ADDR+KSEG0_BASE_ADDR)
#define	DRAM0_END_KSEG0_ADDR		(DRAM0_END_PHYS_ADDR+KSEG0_BASE_ADDR)
#define	DRAM1_BASE_KSEG0_ADDR		(DRAM1_BASE_PHYS_ADDR+KSEG0_BASE_ADDR)
#define	DRAM1_END_KSEG0_ADDR		(DRAM1_END_PHYS_ADDR+KSEG0_BASE_ADDR)
#define	PCI_IO_BASE_KSEG0_ADDR		(PCI_IO_BASE_PHYS_ADDR+KSEG0_BASE_ADDR)
#define	PCI_MEMORY_BASE_KSEG0_ADDR	(PCI_MEMORY_BASE_PHYS_ADDR+KSEG0_BASE_ADDR)
#define	GALILEO_BASE_KSEG0_ADDR		(GALILEO_BASE_PHYS_ADDR+KSEG0_BASE_ADDR)
#define	SHARED_MEM_BASE_KSEG0_ADDR	(SHARED_MEM_BASE_PHYS_ADDR+KSEG0_BASE_ADDR)
#define	RTC_REG_BASE_KSEG0_ADDR		(RTC_REG_BASE_PHYS_ADDR+KSEG0_BASE_ADDR)
#define	DUART_BASE_KSEG0_ADDR		(DUART_BASE_PHYS_ADDR+KSEG0_BASE_ADDR)
#define	CPU_LEDS_KSEG0_ADDR			(CPU_LEDS_PHYS_ADDR+KSEG0_BASE_ADDR)
#define	DRAM_CONFIG_REG_KSEG0_ADDR	(DRAM_CONFIG_REG_PHYS_ADDR+KSEG0_BASE_ADDR)
#define	WATCHDOG_TIMER_KSEG0_ADDR	(WATCHDOG_TIMER_PHYS_ADDR+KSEG0_BASE_ADDR)
#define	CAM_BASE_KSEG0_ADDR			(CAM_BASE_PHYS_ADDR+KSEG0_BASE_ADDR)
#define	CONFIG_REG0_KSEG0_ADDR		(CONFIG_REG0_BASE_PHYS_ADDR+KSEG0_BASE_ADDR)
#define	CONFIG_REG1_KSEG0_ADDR		(CONFIG_REG1_BASE_PHYS_ADDR+KSEG0_BASE_ADDR)
#define	BOOT_FLASH_BASE_KSEG0_ADDR	(BOOT_FLASH_BASE_PHYS_ADDR+KSEG0_BASE_ADDR)
#define	BOOT_FLASH_END_KSEG0_ADDR	(BOOT_FLASH_END_PHYS_ADDR+KSEG0_BASE_ADDR)
#define	FLASH_BASE_KSEG0_ADDR		(FLASH_BASE_PHYS_ADDR+KSEG0_BASE_ADDR)
#define	FLASH_END_KSEG0_ADDR		(FLASH_END_PHYS_ADDR+KSEG0_BASE_ADDR)

#ifdef INCLUDE_ODYSSEY
#define UART_PORTA_KSEG0_ADDR		(UART_PORTA_PHY_ADDR + KSEG0_BASE_ADDR)
#define UART_PORTB_KSEG0_ADDR		(UART_PORTB_PHY_ADDR + KSEG0_BASE_ADDR)
#define UART_PORTC_KSEG0_ADDR		(UART_PORTC_PHY_ADDR + KSEG0_BASE_ADDR)
#define UART_PORTD_KSEG0_ADDR		(UART_PORTD_PHY_ADDR + KSEG0_BASE_ADDR)
#define UART_PORTE_KSEG0_ADDR		(UART_PORTE_PHY_ADDR + KSEG0_BASE_ADDR)
#define UART_PORTF_KSEG0_ADDR		(UART_PORTF_PHY_ADDR + KSEG0_BASE_ADDR)
#define UART_PORTG_KSEG0_ADDR		(UART_PORTG_PHY_ADDR + KSEG0_BASE_ADDR)
#define UART_PORTH_KSEG0_ADDR		(UART_PORTH_PHY_ADDR + KSEG0_BASE_ADDR)
#endif /* INCLUDE_ODYSSEY */



/*
** And now, the REAL Address Space
*/
#define	DRAM0_BASE_ADDR				(DRAM0_BASE_KSEG1_ADDR)
#define	DRAM0_END_ADDR				(DRAM0_END_KSEG1_ADDR)
#define	DRAM1_BASE_ADDR				(DRAM1_BASE_KSEG1_ADDR)
#define	DRAM1_END_ADDR				(DRAM1_END_KSEG1_ADDR)
#define	PCI_IO_BASE_ADDR			(PCI_IO_BASE_KSEG1_ADDR)
#define	PCI_MEMORY_BASE_ADDR		(PCI_MEMORY_BASE_KSEG1_ADDR)
#define	GALILEO_BASE_ADDR			(GALILEO_BASE_KSEG1_ADDR)
#define	SHARED_MEM_BASE_ADDR		(SHARED_MEM_BASE_KSEG1_ADDR)
#define	RTC_REG_BASE_ADDR			(RTC_REG_BASE_KSEG1_ADDR)
#define	DUART_BASE_ADDR				(DUART_BASE_KSEG1_ADDR)
#define	CPU_LEDS_ADDR				(CPU_LEDS_KSEG1_ADDR)
#define	DRAM_CONFIG_REG_ADDR		(DRAM_CONFIG_REG_KSEG1_ADDR)
#define	WATCHDOG_TIMER_ADDR			(WATCHDOG_TIMER_KSEG1_ADDR)
#define	CAM_BASE_ADDR				(CAM_BASE_KSEG1_ADDR)
#define	CONFIG_REG0_ADDR			(CONFIG_REG0_KSEG1_ADDR)
#define	CONFIG_REG1_ADDR			(CONFIG_REG1_KSEG1_ADDR)
#define	BOOT_FLASH_BASE_ADDR		(BOOT_FLASH_BASE_KSEG1_ADDR)
#define	BOOT_FLASH_END_ADDR			(BOOT_FLASH_END_KSEG1_ADDR)
#define	FLASH_BASE_ADDR				(FLASH_BASE_KSEG1_ADDR)
#define	FLASH_END_ADDR				(FLASH_END_KSEG1_ADDR)

#ifdef INCLUDE_ODYSSEY
#define UART_PORTA_BASE_ADDR			(UART_PORTA_KSEG1_ADDR)
#define UART_PORTB_BASE_ADDR			(UART_PORTB_KSEG1_ADDR)
#define UART_PORTC_BASE_ADDR			(UART_PORTC_KSEG1_ADDR)
#define UART_PORTD_BASE_ADDR			(UART_PORTD_KSEG1_ADDR)
#endif /* INCLUDE_ODYSSEY */

/*
** Interrupt Assignments
*/
#ifndef INCLUDE_ODYSSEY

#define	ALL_INT_MASK			0x0000FF00
#define	DUART_INT			0x00004000	/* Int 4 */
#define	FPGA_INT			0x00002000	/* Int 3 */
#define	GT_PCI_INT			0x00000800	/* Int 1 */
#define	GT_CPU_INT			0x00000400	/* Int 0 */
#define	SW_INT_1			0x00000200


#define	DUART_INT_INDEX		4
#define	FPGA_INT_INDEX		3
#define	GT_PCI_INT_INDEX	1
#define	GT_CPU_INT_INDEX	0

#else /* INCLUDE_ODYSSEY */

#define	ALL_INT_MASK			0x0000FF00
#define	DUART_INT			0x00001000	/* Int 2 */
#define	FPGA_INT			0x00002000	/* Int 3 */
#define	GT_PCI_INT			0x00000800	/* Int 1 */
#define	GT_CPU_INT			0x00000400	/* Int 0 */
#define	SW_INT_1			0x00000200


#ifdef	CONFIG_E2
#define	DUART_INT_INDEX		4
#else
#define	DUART_INT_INDEX		3
#endif
#define	FPGA_INT_INDEX		2
#define	GT_PCI_INT_INDEX	1
#define	GT_CPU_INT_INDEX	0

#endif /* INCLUDE_ODYSSEY */


/* Definitions for the slot Number */
#define	SLOT_ADDR_HBC0		0x00
#define	SLOT_ADDR_HBC1		0x01
#define	SLOT_ADDR_FCH0		0x08
#define	SLOT_ADDR_FCH1		0x09
#define	SLOT_ADDR_FCH2		0x0A
#define	SLOT_ADDR_FCH3		0x0B
#define	SLOT_ADDR_DDH0		0x0C
#define	SLOT_ADDR_DDH1		0x0D
#define	SLOT_ADDR_DDH2		0x0E
#define	SLOT_ADDR_DDH3		0x0F
#define	SLOT_ADDR_SSD0		0x10
#define	SLOT_ADDR_SSD1		0x11
#define	SLOT_ADDR_SSD2		0x12
#define	SLOT_ADDR_SSD3		0x13
#define	SLOT_ADDR_SSD4		0x14
#define	SLOT_ADDR_SSD5		0x15
#define	SLOT_ADDR_SSD6		0x16
#define	SLOT_ADDR_SSD7		0x17
#define	SLOT_ADDR_RAC0		0x18
#define	SLOT_ADDR_ASP0		0x19
#define	SLOT_ADDR_ASP1		0x1A
#define	SLOT_ADDR_NIC0		0x1B
#define	SLOT_ADDR_RAC1		0x1C
#define	SLOT_ADDR_ASP2		0x1D
#define	SLOT_ADDR_ASP3		0x1E
#define	SLOT_ADDR_NIC1		0x1F

/*
** Etc.
*/
#define MAX_FLASH_BANKS		4	/* boot[0], main[1:3] */
#define FLASH_BANK1			1
#define FLASH_BANK2			2
#define FLASH_BANK3			3

#define LED_REG				((unsigned char *)(CPU_LEDS_ADDR))
#define CPU_LED1			0x01 /* 02 */
#define CPU_LED2			0x02 /* 04 */
#define CPU_LED3			0x04 /* 01 */
#define CPU_LED4			0x08 /* 20 */
#define CPU_LED5			0x10 /* 40 */
#define CPU_LED6			0x20 /* 08 */
#define CPU_LED7			0x40 /* 80 */
#define CPU_LED8			0x80 /* 10 */

#define WDOG_REG			((unsigned char *)(WATCHDOG_TIMER_ADDR))

#define MFG_MODE			0	/* (*REGISTER & BITMASK) */

/*
 * MIPS CPU CoProcessor Register definitions of Odyssey
 */

#define C0_PAGEMASK_DEFAULT		PM_M_16M			
#endif
